return {{[ [[C1]] ] = {2},[ [[C3]] ] = {3},[ [[C2]] ] = {4},},
{[ [[T2]] ] = {5},[ [[T3]] ] = {6},[ [[T1]] ] = {7},[ [[T7]] ] = {8},[ [[T6]] ] = {9},[ [[T5]] ] = {10},[ [[T4]] ] = {11},},
{[ [[T2]] ] = {12},[ [[T3]] ] = {13},[ [[T1]] ] = {14},[ [[T7]] ] = {15},[ [[T6]] ] = {16},[ [[T5]] ] = {17},[ [[T4]] ] = {18},},
{[ [[T2]] ] = {19},[ [[T3]] ] = {20},[ [[T1]] ] = {21},[ [[T7]] ] = {22},[ [[T6]] ] = {23},[ [[T5]] ] = {24},[ [[T4]] ] = {25},},
{[ [[flimsy leather boots]] ] = [[flimsy-leather-boots]],[ [[rusted plate boots]] ] = [[rusted-plate-boots]],[ [[decayed slippers]] ] = [[decayed-slippers]],},
{[ [[a rusted plate bracer]] ] = [[rusted-plate-bracer]],[ [[a decayed bracelet]] ] = [[decayed-bracelet]],[ [[a flimsy leather bracer]] ] = [[flimsy-leather-bracer]],},
{[ [[flimsy leather gloves]] ] = [[flimsy-leather-gloves]],[ [[decayed mittens]] ] = [[decayed-mittens]],[ [[rusted gauntlets]] ] = [[rusted-gauntlets]],},
{[ [[a rusted plate]] ] = [[rusted-plate]],[ [[flimsy leather jerkin]] ] = [[flimsy-leather-jerkin]],[ [[a decayed robe]] ] = [[decayed-robe]],},
{[ [[flimsy leather leggings]] ] = [[flimsy-leather-leggings]],[ [[rusted greaves]] ] = [[rusted-greaves]],[ [[decayed leggings]] ] = [[decayed-leggings]],},
{[ [[decayed sleeves]] ] = [[decayed-sleeves]],[ [[flimsy leather sleeves]] ] = [[flimsy-leather-sleeves]],[ [[rusted vambraces]] ] = [[rusted-vambraces]],},
{[ [[a decayed turban]] ] = [[decayed-turban]],[ [[a flimsy leather cap]] ] = [[flimsy-leather-cap]],[ [[a rusted helm]] ] = [[rusted-helm]],},
{[ [[creased leather boots]] ] = [[creased-leather-boots]],[ [[corroded boots]] ] = [[corroded-boots]],[ [[tarnished plate boots]] ] = [[tarnished-plate-boots]],[ [[worn slippers]] ] = [[worn-slippers]],},
{[ [[worn bracelet]] ] = [[worn-bracelet]],[ [[creased leather bracer]] ] = [[creased-leather-bracer]],[ [[tarnished plate bracer]] ] = [[tarnished-plate-bracer]],[ [[corroded wristband]] ] = [[corroded-wristband]],},
{[ [[corroded gloves]] ] = [[corroded-gloves]],[ [[tarnished gauntlets]] ] = [[tarnished-gauntlets]],[ [[creased leather gloves]] ] = [[creased-leather-gloves]],[ [[worn mittens]] ] = [[worn-mittens]],},
{[ [[a corroded jerkin]] ] = [[corroded-jerkin]],[ [[tarnished plate]] ] = [[tarnished-plate]],[ [[worn robe]] ] = [[worn-robe]],[ [[creased leather tunic]] ] = [[creased-leather-tunic]],},
{[ [[corroded pants]] ] = [[corroded-pants]],[ [[creased leather leggings]] ] = [[creased-leather-leggings]],[ [[worn leggings]] ] = [[worn-leggings]],[ [[tarnished greaves]] ] = [[tarnished-greaves]],},
{[ [[corroded vambraces]] ] = [[corroded-vambraces]],[ [[worn sleeves]] ] = [[worn-sleeves]],[ [[creased leather sleeves]] ] = [[creased-leather-sleeves]],[ [[tarnished vambraces]] ] = [[tarnished-vambraces]],},
{[ [[a corroded cap]] ] = [[corroded-cap]],[ [[tarnished helm]] ] = [[tarnished-helm]],[ [[worn turban]] ] = [[worn-turban]],[ [[creased leather hood]] ] = [[creased-leather-hood]],},
{[ [[crushed leather boots]] ] = [[crushed-leather-boots]],[ [[burned slippers]] ] = [[burned-slippers]],[ [[crushed plate boots]] ] = [[crushed-plate-boots]],[ [[burned boots]] ] = [[burned-boots]],},
{[ [[a burned wristband]] ] = [[burned-wristband]],[ [[crushed plate bracer]] ] = [[crushed-plate-bracer]],[ [[burned bracelet]] ] = [[burned-bracelet]],[ [[crushed leather bracer]] ] = [[crushed-leather-bracer]],},
{[ [[crushed gauntlets]] ] = [[crushed-gauntlets]],[ [[burned gloves]] ] = [[burned-gloves]],[ [[crushed leather gloves]] ] = [[crushed-leather-gloves]],[ [[burned mittens]] ] = [[burned-mittens]],},
{[ [[crushed leather tunic]] ] = [[crushed-leather-tunic]],[ [[burned jerkin]] ] = [[burned-jerkin]],[ [[a crushed plate]] ] = [[crushed-plate]],[ [[a burned robe]] ] = [[burned-robe]],},
{[ [[crushed leather leggings]] ] = [[crushed-leather-leggings]],[ [[crushed greaves]] ] = [[crushed-greaves]],[ [[burned pants]] ] = [[burned-pants]],[ [[burned leggings]] ] = [[burned-leggings]],},
{[ [[burned vambraces]] ] = [[burned-vambraces]],[ [[crushed leather sleeves]] ] = [[crushed-leather-sleeves]],[ [[crushed vambraces]] ] = [[crushed-vambraces]],[ [[burned sleeves]] ] = [[burned-sleeves]],},
{[ [[a crushed helm]] ] = [[crushed-helm]],[ [[a crushed hood]] ] = [[crushed-hood]],[ [[a burned cap]] ] = [[burned-cap]],[ [[a burned turban]] ] = [[burned-turban]],},
}
