return {{[ [[a flawed agate]] ] = {2},[ [[a kuwagata]] ] = {3},[ [[a runestone]] ] = {4},[ [[a dragon's fist mace]] ] = {5},[ [[Boots of the Protector]] ] = {6},[ [[a steel battle-axe]] ] = {7},[ [[a leather jerkin of the 3rd Eldorian Guard]] ] = {8},[ [[a token of the 3rd Black Legion]] ] = {9},[ [[boots of the 3rd Eldorian Guard]] ] = {10},[ [[a clear potion of remove poison]] ] = {11},[ [[a leather water skin]] ] = {12},[ [[a Fiery Red drakling scale]] ] = {13},[ [[a lightweight baton]] ] = {14},[ [[a legendary ice fang]] ] = {15},[ [[a speckled egg]] ] = {16},[ [[the Flail of Yeenoghu]] ] = {17},[ [[Tunic of the Protector]] ] = {18},[ [[a small potion]] ] = {19},[ [[the Fire Goddess's skirt]] ] = {20},[ [[a vulture feather]] ] = {21},[ [[a radiant dagger]] ] = {22},[ [[a shoot of thyme]] ] = {23},[ [[a dark potion]] ] = {24},[ [[a cloth sack]] ] = {25},[ [[a Chaos orb]] ] = {26},[ [[fur trimmed hide bracers]] ] = {27},[ [[a bracelet with boar images on it]] ] = {28},[ [[a stone necklace]] ] = {29},[ [[a wand of the 3rd Black Legion]] ] = {30},[ [[a maul]] ] = {31},[ [[decayed leggings]] ] = {32},[ [[a scroll of identify]] ] = {33},[ [[the Kinship Broadsword]] ] = {34},[ [[leggings of the 3rd Eldorian Guard]] ] = {35},[ [[a grey cloth shirt]] ] = {36},[ [[a monocle]] ] = {37},[ [[a seashell shard]] ] = {38},[ [[an iridescent sword]] ] = {39},[ [[a bark canoe]] ] = {40},[ [[a gray scroll of recall]] ] = {41},[ [[a bluish-silver helm]] ] = {42},[ [[Studded Gauntlets of the Protector]] ] = {43},[ [[a spellbook]] ] = {44},[ [[a zebra skin cloak]] ] = {45},[ [[the aspen key]] ] = {46},[ [[Woodsmen Bracer]] ] = {47},[ [[a wolf fur cloak]] ] = {48},[ [[a badge of the 3rd Black Legion]] ] = {49},[ [[a skull of the 3rd Eldorian Guard]] ] = {50},[ [[a golden robe]] ] = {51},[ [[a citrine shard]] ] = {52},[ [[a longsword of the 3rd Eldorian Guard]] ] = {53},[ [[Woodsmen Embroidered Leather Jerkin]] ] = {54},[ [[the Shadow Lance]] ] = {55},[ [[a vial of sparks]] ] = {56},[ [[a blue vial]] ] = {57},[ [[a skull of the 3rd Black Legion]] ] = {58},[ [[a striking jade necklace]] ] = {59},[ [[a diamond engagement ring]] ] = {60},[ [[Sleeves of the Protector]] ] = {61},[ [[an octant]] ] = {62},[ [[a bear claw tattoo]] ] = {63},[ [[a thin copper bracelet]] ] = {64},[ [[an ornamental christmas ball]] ] = {65},[ [[a bird wing tattoo]] ] = {66},[ [[a jagged greataxe]] ] = {67},[ [[trainee greaves]] ] = {68},[ [[a leather saddle]] ] = {69},[ [[a black leather bag]] ] = {70},[ [[a dwarven war axe]] ] = {71},[ [[a robe of the 3rd Eldorian Guard]] ] = {72},[ [[a crocodile-tooth necklace]] ] = {73},[ [[a spyglass]] ] = {74},[ [[Leggings of the Protector]] ] = {75},[ [[an alabaster-pommelled broadsword]] ] = {76},[ [[a clear vial]] ] = {77},[ [[Helm of the Protector]] ] = {78},[ [[a pale circlet]] ] = {79},[ [[Bracer of the Protector]] ] = {80},[ [[a crushed aquamarine]] ] = {81},[ [[wolf eye tattoos]] ] = {82},[ [[a broken dragon's fist mace]] ] = {83},[ [[a ring of the 3rd Black Legion]] ] = {84},[ [[a black and gold harp]] ] = {85},[ [[a bottle of nostrum]] ] = {86},[ [[a bat tooth necklace]] ] = {87},[ [[the Shield of Darkness]] ] = {88},[ [[the jewel of the heart]] ] = {89},},
{[ [[Flags]] ] = {90},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a flawed agate]],[ [[Weight]] ] = 0.01,[ [[Value]] ] = 4000,[ [[Level]] ] = 0,[ [[Apply]] ] = {91},},
{[ [[Flags]] ] = {92},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a kuwagata]],[ [[Weight]] ] = 2,[ [[Value]] ] = 750,[ [[Worn]] ] = [[HEAD]],[ [[Level]] ] = 20,[ [[Apply]] ] = {93},},
{[ [[Flags]] ] = {94},[ [[Type]] ] = [[KEY]],[ [[Name]] ] = [[a runestone]],[ [[Weight]] ] = 0.75,[ [[Value]] ] = 0,[ [[Level]] ] = 0,},
{[ [[Dice]] ] = [[4D4]],[ [[Worn]] ] = [[one-handed]],[ [[Flags]] ] = {95},[ [[AvgDmg]] ] = [[10.0]],[ [[Name]] ] = [[a dragon's fist mace]],[ [[Weight]] ] = 7,[ [[Value]] ] = 2000,[ [[Level]] ] = 60,[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {96},},
{[ [[Type]] ] = [[ARMOR]],[ [[Flags]] ] = {97},[ [[Level]] ] = 41,[ [[Name]] ] = [[Boots of the Protector]],[ [[Weight]] ] = 3.57,[ [[Value]] ] = 0,[ [[Worn]] ] = [[FEET]],[ [[Provides]] ] = {98},[ [[Apply]] ] = {99},},
{[ [[Dice]] ] = [[2D6]],[ [[Worn]] ] = [[one-handed]],[ [[Flags]] ] = {100},[ [[AvgDmg]] ] = [[7.0]],[ [[Name]] ] = [[a steel battle-axe]],[ [[Weight]] ] = 5,[ [[Value]] ] = 500,[ [[Level]] ] = 35,[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {101},},
{[ [[Flags]] ] = {102},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a leather jerkin of the 3rd Eldorian Guard]],[ [[Weight]] ] = 8,[ [[Value]] ] = 0,[ [[Worn]] ] = [[BODY]],[ [[Level]] ] = 12,[ [[Apply]] ] = {103},},
{[ [[Flags]] ] = {104},[ [[Type]] ] = [[TRASH]],[ [[Name]] ] = [[a token of the 3rd Black Legion]],[ [[Weight]] ] = 1,[ [[Value]] ] = 0,[ [[Level]] ] = 8,},
{[ [[Flags]] ] = {105},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[boots of the 3rd Eldorian Guard]],[ [[Weight]] ] = 2.3,[ [[Value]] ] = 0,[ [[Worn]] ] = [[FEET]],[ [[Level]] ] = 12,[ [[Apply]] ] = {106},},
{[ [[Flags]] ] = {107},[ [[Type]] ] = [[POTION]],[ [[Name]] ] = [[a clear potion of remove poison]],[ [[Weight]] ] = 0.15,[ [[Value]] ] = 500,[ [[Level]] ] = 1,[ [[Casts]] ] = {108},},
{[ [[Type]] ] = [[LIQCONTAINER]],[ [[LiquidCapacity]] ] = [[256]],[ [[Flags]] ] = {109},[ [[Name]] ] = [[a leather water skin]],[ [[Weight]] ] = 2,[ [[Value]] ] = 10,[ [[Worn]] ] = [[HOLD]],[ [[Liquid]] ] = [[water]],[ [[Level]] ] = 1,},
{[ [[Flags]] ] = {110},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a Fiery Red drakling scale]],[ [[Weight]] ] = 0.5,[ [[Value]] ] = 0,[ [[Worn]] ] = [[BADGE]],[ [[Level]] ] = 1,[ [[Apply]] ] = {111},},
{[ [[Dice]] ] = [[3D6]],[ [[Specials]] ] = {112},[ [[Flags]] ] = {113},[ [[AvgDmg]] ] = [[10.5]],[ [[Name]] ] = [[a lightweight baton]],[ [[Weight]] ] = 2.4,[ [[Value]] ] = 34902,[ [[Level]] ] = 90,[ [[Type]] ] = [[WEAPON]],[ [[Worn]] ] = [[one-handed]],},
{[ [[Flags]] ] = {114},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a legendary ice fang]],[ [[Weight]] ] = 0.2,[ [[Value]] ] = 1900,[ [[Worn]] ] = [[EAR]],[ [[Level]] ] = 43,[ [[Apply]] ] = {115},},
{[ [[Type]] ] = [[CONTAINER]],[ [[Is]] ] = {116},[ [[Reduction]] ] = [[0%]],[ [[Flags]] ] = {117},[ [[Worn]] ] = [[HOLD]],[ [[Name]] ] = [[a speckled egg]],[ [[Weight]] ] = 0.2,[ [[Value]] ] = 0,[ [[Level]] ] = 5,[ [[Capacity]] ] = [[20]],[ [[Apply]] ] = {118},},
{[ [[Dice]] ] = [[4D2]],[ [[AvgDmg]] ] = [[6.0]],[ [[Flags]] ] = {119},[ [[Level]] ] = 25,[ [[Name]] ] = [[the Flail of Yeenoghu]],[ [[Weight]] ] = 12,[ [[Value]] ] = 500,[ [[Worn]] ] = [[one-handed]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {120},},
{[ [[Flags]] ] = {121},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[Tunic of the Protector]],[ [[Weight]] ] = 9.3,[ [[Value]] ] = 0,[ [[Worn]] ] = [[BODY]],[ [[Level]] ] = 41,[ [[Apply]] ] = {122},},
{[ [[Flags]] ] = {123},[ [[Type]] ] = [[POTION]],[ [[Name]] ] = [[a small potion]],[ [[Weight]] ] = 0.1,[ [[Value]] ] = 10,[ [[Level]] ] = 17,[ [[Casts]] ] = {124},},
{[ [[Flags]] ] = {125},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[the Fire Goddess's skirt]],[ [[Weight]] ] = 2,[ [[Value]] ] = 10000,[ [[Worn]] ] = [[WAIST]],[ [[Level]] ] = 5,[ [[Apply]] ] = {126},},
{[ [[Flags]] ] = {127},[ [[Type]] ] = [[PEN]],[ [[Name]] ] = [[a vulture feather]],[ [[Weight]] ] = 0.04,[ [[Value]] ] = 0,[ [[Worn]] ] = [[HOLD]],[ [[Level]] ] = 15,[ [[Apply]] ] = {128},},
{[ [[Dice]] ] = [[5D2]],[ [[AvgDmg]] ] = [[7.5]],[ [[Flags]] ] = {129},[ [[Level]] ] = 30,[ [[Name]] ] = [[a radiant dagger]],[ [[Weight]] ] = 0.5,[ [[Value]] ] = 600,[ [[Worn]] ] = [[one-handed]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {130},},
{[ [[Flags]] ] = {131},[ [[Type]] ] = [[FOOD]],[ [[Name]] ] = [[a shoot of thyme]],[ [[Weight]] ] = 0.1,[ [[Value]] ] = 0,[ [[Level]] ] = 0,[ [[Fillingness]] ] = [[1]],},
{[ [[Flags]] ] = {132},[ [[Type]] ] = [[POTION]],[ [[Name]] ] = [[a dark potion]],[ [[Weight]] ] = 0.1,[ [[Value]] ] = 10,[ [[Level]] ] = 17,[ [[Casts]] ] = {133},},
{[ [[Type]] ] = [[CONTAINER]],[ [[Capacity]] ] = [[60]],[ [[Reduction]] ] = [[0%]],[ [[Flags]] ] = {134},[ [[Name]] ] = [[a cloth sack]],[ [[Weight]] ] = 0.6,[ [[Value]] ] = 1,[ [[Level]] ] = 1,[ [[Worn]] ] = [[HOLD OBELT]],},
{[ [[Type]] ] = [[LIGHT]],[ [[Flags]] ] = {135},[ [[Hours]] ] = [[Infinate]],[ [[Name]] ] = [[a Chaos orb]],[ [[Weight]] ] = 2,[ [[Value]] ] = 0,[ [[Level]] ] = 65,[ [[Worn]] ] = [[HOLD HOVER]],[ [[Apply]] ] = {136},},
{[ [[Flags]] ] = {137},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[fur trimmed hide bracers]],[ [[Weight]] ] = 3.7,[ [[Value]] ] = 500,[ [[Worn]] ] = [[ARMS]],[ [[Level]] ] = 30,[ [[Apply]] ] = {138},},
{[ [[Flags]] ] = {139},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a bracelet with boar images on it]],[ [[Weight]] ] = 0.25,[ [[Value]] ] = 0,[ [[Worn]] ] = [[WRIST]],[ [[Level]] ] = 5,[ [[Apply]] ] = {140},},
{[ [[Flags]] ] = {141},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a stone necklace]],[ [[Weight]] ] = 0.8,[ [[Value]] ] = 40,[ [[Worn]] ] = [[NECK WRIST]],[ [[Level]] ] = 35,[ [[Apply]] ] = {142},},
{[ [[Flags]] ] = {143},[ [[Type]] ] = [[TRASH]],[ [[Name]] ] = [[a wand of the 3rd Black Legion]],[ [[Weight]] ] = 1.4,[ [[Value]] ] = 0,[ [[Worn]] ] = [[HOLD]],[ [[Level]] ] = 8,},
{[ [[Dice]] ] = [[4D2]],[ [[Level]] ] = 15,[ [[Flags]] ] = {144},[ [[Worn]] ] = [[one-handed]],[ [[Name]] ] = [[a maul]],[ [[Weight]] ] = 6.5,[ [[Value]] ] = 400,[ [[AvgDmg]] ] = [[6.0]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {145},},
{[ [[Flags]] ] = {146},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[decayed leggings]],[ [[Weight]] ] = 2.4,[ [[Value]] ] = 0,[ [[Level]] ] = 0,[ [[Apply]] ] = {147},},
{[ [[Flags]] ] = {148},[ [[Type]] ] = [[SCROLL]],[ [[Name]] ] = [[a scroll of identify]],[ [[Weight]] ] = 0.1,[ [[Value]] ] = 1,[ [[Worn]] ] = [[HOLD]],[ [[Casts]] ] = {149},[ [[Level]] ] = 1,},
{[ [[Dice]] ] = [[3D4]],[ [[Worn]] ] = [[one-handed]],[ [[Flags]] ] = {150},[ [[AvgDmg]] ] = [[7.5]],[ [[Name]] ] = [[the Kinship Broadsword]],[ [[Weight]] ] = 5,[ [[Value]] ] = 1500,[ [[Level]] ] = 35,[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {151},},
{[ [[Flags]] ] = {152},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[leggings of the 3rd Eldorian Guard]],[ [[Weight]] ] = 4.9,[ [[Value]] ] = 0,[ [[Worn]] ] = [[LEGS]],[ [[Level]] ] = 12,[ [[Apply]] ] = {153},},
{[ [[Flags]] ] = {154},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a grey cloth shirt]],[ [[Weight]] ] = 0.6,[ [[Value]] ] = 0,[ [[Worn]] ] = [[BODY]],[ [[Level]] ] = 1,[ [[Apply]] ] = {155},},
{[ [[Type]] ] = [[TREASURE]],[ [[Flags]] ] = {156},[ [[Worn]] ] = [[EYES]],[ [[Name]] ] = [[a monocle]],[ [[Weight]] ] = 0.07,[ [[Value]] ] = 250,[ [[Level]] ] = 40,[ [[Provides]] ] = {157},[ [[Apply]] ] = {158},},
{[ [[Flags]] ] = {159},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a seashell shard]],[ [[Weight]] ] = 0.4,[ [[Value]] ] = 15,[ [[Worn]] ] = [[HOLD]],[ [[Level]] ] = 5,[ [[Apply]] ] = {160},},
{[ [[Dice]] ] = [[2D8]],[ [[AvgDmg]] ] = [[9.0]],[ [[Flags]] ] = {161},[ [[Level]] ] = 35,[ [[Name]] ] = [[an iridescent sword]],[ [[Weight]] ] = 3,[ [[Value]] ] = 3000,[ [[Worn]] ] = [[one-handed]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {162},},
{[ [[Flags]] ] = {163},[ [[Type]] ] = [[BOAT]],[ [[Name]] ] = [[a bark canoe]],[ [[Weight]] ] = 20,[ [[Value]] ] = 1,[ [[Worn]] ] = [[HOLD]],[ [[Level]] ] = 10,},
{[ [[Flags]] ] = {164},[ [[Type]] ] = [[SCROLL]],[ [[Name]] ] = [[a gray scroll of recall]],[ [[Weight]] ] = 0.12,[ [[Value]] ] = 3000,[ [[Worn]] ] = [[HOLD]],[ [[Casts]] ] = {165},[ [[Level]] ] = 1,},
{[ [[Flags]] ] = {166},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a bluish-silver helm]],[ [[Weight]] ] = 6.75,[ [[Value]] ] = 700,[ [[Worn]] ] = [[HEAD]],[ [[Level]] ] = 35,[ [[Apply]] ] = {167},},
{[ [[Flags]] ] = {168},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[Studded Gauntlets of the Protector]],[ [[Weight]] ] = 1.1,[ [[Value]] ] = 0,[ [[Worn]] ] = [[HANDS]],[ [[Level]] ] = 41,[ [[Apply]] ] = {169},},
{[ [[Flags]] ] = {170},[ [[Type]] ] = [[SPELLBOOK]],[ [[Name]] ] = [[a spellbook]],[ [[Weight]] ] = 2.5,[ [[Value]] ] = 1,[ [[Worn]] ] = [[HOLD]],[ [[Level]] ] = 1,},
{[ [[Flags]] ] = {171},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a zebra skin cloak]],[ [[Weight]] ] = 5,[ [[Value]] ] = 0,[ [[Worn]] ] = [[ABOUT]],[ [[Level]] ] = 15,[ [[Apply]] ] = {172},},
{[ [[Flags]] ] = {173},[ [[Type]] ] = [[KEY]],[ [[Name]] ] = [[the aspen key]],[ [[Weight]] ] = 0.05,[ [[Value]] ] = 0,[ [[Worn]] ] = [[HOLD]],[ [[Level]] ] = 1,},
{[ [[Flags]] ] = {174},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[Woodsmen Bracer]],[ [[Weight]] ] = 0.64,[ [[Value]] ] = 0,[ [[Worn]] ] = [[WRIST]],[ [[Level]] ] = 21,[ [[Apply]] ] = {175},},
{[ [[Flags]] ] = {176},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a wolf fur cloak]],[ [[Weight]] ] = 5,[ [[Value]] ] = 200,[ [[Worn]] ] = [[ABOUT]],[ [[Level]] ] = 15,[ [[Apply]] ] = {177},},
{[ [[Flags]] ] = {178},[ [[Type]] ] = [[TRASH]],[ [[Name]] ] = [[a badge of the 3rd Black Legion]],[ [[Weight]] ] = 0.09,[ [[Value]] ] = 0,[ [[Worn]] ] = [[BADGE]],[ [[Level]] ] = 8,},
{[ [[Flags]] ] = {179},[ [[Type]] ] = [[TRASH]],[ [[Name]] ] = [[a skull of the 3rd Eldorian Guard]],[ [[Weight]] ] = 2.2,[ [[Value]] ] = 0,[ [[Level]] ] = 8,},
{[ [[Flags]] ] = {180},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a golden robe]],[ [[Weight]] ] = 3,[ [[Value]] ] = 500,[ [[Worn]] ] = [[BODY]],[ [[Level]] ] = 30,[ [[Apply]] ] = {181},},
{[ [[Flags]] ] = {182},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a citrine shard]],[ [[Weight]] ] = 0.01,[ [[Value]] ] = 1500,[ [[Level]] ] = 0,[ [[Apply]] ] = {183},},
{[ [[Dice]] ] = [[2D4]],[ [[Flags]] ] = {184},[ [[AvgDmg]] ] = [[5.0]],[ [[Name]] ] = [[a longsword of the 3rd Eldorian Guard]],[ [[Weight]] ] = 3,[ [[Value]] ] = 0,[ [[Level]] ] = 12,[ [[Type]] ] = [[WEAPON]],[ [[Worn]] ] = [[one-handed]],},
{[ [[Flags]] ] = {185},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[Woodsmen Embroidered Leather Jerkin]],[ [[Weight]] ] = 8,[ [[Value]] ] = 0,[ [[Worn]] ] = [[BODY]],[ [[Level]] ] = 21,[ [[Apply]] ] = {186},},
{[ [[Dice]] ] = [[4D2]],[ [[Level]] ] = 20,[ [[Flags]] ] = {187},[ [[Worn]] ] = [[one-handed]],[ [[Name]] ] = [[the Shadow Lance]],[ [[Weight]] ] = 3,[ [[Value]] ] = 200,[ [[AvgDmg]] ] = [[6.0]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {188},},
{[ [[Flags]] ] = {189},[ [[Type]] ] = [[POTION]],[ [[Name]] ] = [[a vial of sparks]],[ [[Weight]] ] = 0,[ [[Value]] ] = 100,[ [[Level]] ] = 5,[ [[Casts]] ] = {190},},
{[ [[Flags]] ] = {191},[ [[Type]] ] = [[POTION]],[ [[Name]] ] = [[a blue vial]],[ [[Weight]] ] = 0.1,[ [[Value]] ] = 10,[ [[Level]] ] = 17,[ [[Casts]] ] = {192},},
{[ [[Flags]] ] = {193},[ [[Type]] ] = [[TRASH]],[ [[Name]] ] = [[a skull of the 3rd Black Legion]],[ [[Weight]] ] = 2.2,[ [[Value]] ] = 0,[ [[Level]] ] = 8,},
{[ [[Flags]] ] = {194},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a striking jade necklace]],[ [[Weight]] ] = 0.6,[ [[Value]] ] = 4500,[ [[Worn]] ] = [[NECK]],[ [[Level]] ] = 20,[ [[Apply]] ] = {195},},
{[ [[Flags]] ] = {196},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a diamond engagement ring]],[ [[Weight]] ] = 0.02,[ [[Value]] ] = 18000,[ [[Worn]] ] = [[FINGER]],[ [[Level]] ] = 1,[ [[Apply]] ] = {197},},
{[ [[Flags]] ] = {198},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[Sleeves of the Protector]],[ [[Weight]] ] = 6.7,[ [[Value]] ] = 0,[ [[Worn]] ] = [[ARMS]],[ [[Level]] ] = 41,[ [[Apply]] ] = {199},},
{[ [[Flags]] ] = {200},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[an octant]],[ [[Weight]] ] = 0.4,[ [[Value]] ] = 0,[ [[Worn]] ] = [[OBELT]],[ [[Level]] ] = 20,[ [[Apply]] ] = {201},},
{[ [[Type]] ] = [[TREASURE]],[ [[Specials]] ] = {202},[ [[Flags]] ] = {203},[ [[Level]] ] = 20,[ [[Name]] ] = [[a bear claw tattoo]],[ [[Weight]] ] = 0.01,[ [[Value]] ] = 3000,[ [[Worn]] ] = [[EYES]],[ [[Provides]] ] = {204},[ [[Apply]] ] = {205},},
{[ [[Flags]] ] = {206},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a thin copper bracelet]],[ [[Weight]] ] = 0.07,[ [[Value]] ] = 0,[ [[Worn]] ] = [[WRIST]],[ [[Level]] ] = 1,[ [[Apply]] ] = {207},},
{[ [[Type]] ] = [[LIGHT]],[ [[Is]] ] = {208},[ [[Flags]] ] = {209},[ [[Name]] ] = [[an ornamental christmas ball]],[ [[Weight]] ] = 0.06,[ [[Value]] ] = 0,[ [[Level]] ] = 1,[ [[Hours]] ] = [[Infinate]],[ [[Worn]] ] = [[EAR OBELT]],},
{[ [[Type]] ] = [[TREASURE]],[ [[Specials]] ] = {210},[ [[Flags]] ] = {211},[ [[Worn]] ] = [[EYES]],[ [[Name]] ] = [[a bird wing tattoo]],[ [[Weight]] ] = 0.01,[ [[Value]] ] = 4000,[ [[Level]] ] = 30,[ [[Provides]] ] = {212},[ [[Apply]] ] = {213},},
{[ [[Dice]] ] = [[3D10]],[ [[Level]] ] = 30,[ [[Flags]] ] = {214},[ [[Worn]] ] = [[two-handed]],[ [[Name]] ] = [[a jagged greataxe]],[ [[Weight]] ] = 12,[ [[Value]] ] = 500,[ [[AvgDmg]] ] = [[16.5]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {215},},
{[ [[Flags]] ] = {216},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[trainee greaves]],[ [[Weight]] ] = 15,[ [[Value]] ] = 0,[ [[Worn]] ] = [[LEGS]],[ [[Level]] ] = 1,[ [[Apply]] ] = {217},},
{[ [[Type]] ] = [[CONTAINER]],[ [[Capacity]] ] = [[200]],[ [[Reduction]] ] = [[0%]],[ [[Flags]] ] = {218},[ [[Name]] ] = [[a leather saddle]],[ [[Weight]] ] = 8,[ [[Value]] ] = 100,[ [[Level]] ] = 10,[ [[Worn]] ] = [[BODY]],[ [[Apply]] ] = {219},},
{[ [[Type]] ] = [[CONTAINER]],[ [[Capacity]] ] = [[5000]],[ [[Reduction]] ] = [[0%]],[ [[Flags]] ] = {220},[ [[Name]] ] = [[a black leather bag]],[ [[Weight]] ] = 1,[ [[Value]] ] = 100,[ [[Level]] ] = 1,[ [[Worn]] ] = [[OBELT]],},
{[ [[Dice]] ] = [[3D9]],[ [[AvgDmg]] ] = [[15.0]],[ [[Flags]] ] = {221},[ [[Level]] ] = 20,[ [[Name]] ] = [[a dwarven war axe]],[ [[Weight]] ] = 4,[ [[Value]] ] = 9000,[ [[Worn]] ] = [[two-handed]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {222},},
{[ [[Flags]] ] = {223},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a robe of the 3rd Eldorian Guard]],[ [[Weight]] ] = 3,[ [[Value]] ] = 0,[ [[Worn]] ] = [[BODY]],[ [[Level]] ] = 12,[ [[Apply]] ] = {224},},
{[ [[Flags]] ] = {225},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a crocodile-tooth necklace]],[ [[Weight]] ] = 1.2,[ [[Value]] ] = 0,[ [[Worn]] ] = [[NECK]],[ [[Level]] ] = 15,[ [[Apply]] ] = {226},},
{[ [[Type]] ] = [[TREASURE]],[ [[Flags]] ] = {227},[ [[Level]] ] = 10,[ [[Name]] ] = [[a spyglass]],[ [[Weight]] ] = 0.75,[ [[Value]] ] = 2000,[ [[Worn]] ] = [[HOLD]],[ [[Provides]] ] = {228},[ [[Apply]] ] = {229},},
{[ [[Flags]] ] = {230},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[Leggings of the Protector]],[ [[Weight]] ] = 8.6,[ [[Value]] ] = 0,[ [[Worn]] ] = [[LEGS]],[ [[Level]] ] = 41,[ [[Apply]] ] = {231},},
{[ [[Dice]] ] = [[4D11]],[ [[Level]] ] = 35,[ [[Flags]] ] = {232},[ [[Worn]] ] = [[two-handed]],[ [[Name]] ] = [[an alabaster-pommelled broadsword]],[ [[Weight]] ] = 2.2,[ [[Value]] ] = 1000,[ [[AvgDmg]] ] = [[24.0]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {233},},
{[ [[Flags]] ] = {234},[ [[Type]] ] = [[POTION]],[ [[Name]] ] = [[a clear vial]],[ [[Weight]] ] = 0.1,[ [[Value]] ] = 100,[ [[Level]] ] = 17,[ [[Casts]] ] = {235},},
{[ [[Type]] ] = [[ARMOR]],[ [[Flags]] ] = {236},[ [[Level]] ] = 41,[ [[Name]] ] = [[Helm of the Protector]],[ [[Weight]] ] = 2.6,[ [[Value]] ] = 0,[ [[Worn]] ] = [[HEAD]],[ [[Provides]] ] = {237},[ [[Apply]] ] = {238},},
{[ [[Type]] ] = [[LIGHT]],[ [[Flags]] ] = {239},[ [[Level]] ] = 15,[ [[Name]] ] = [[a pale circlet]],[ [[Weight]] ] = 1.4,[ [[Value]] ] = 5000,[ [[Worn]] ] = [[HEAD]],[ [[Hours]] ] = [[400]],[ [[Apply]] ] = {240},},
{[ [[Flags]] ] = {241},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[Bracer of the Protector]],[ [[Weight]] ] = 0.91,[ [[Value]] ] = 0,[ [[Worn]] ] = [[WRIST]],[ [[Level]] ] = 41,[ [[Apply]] ] = {242},},
{[ [[Flags]] ] = {243},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a crushed aquamarine]],[ [[Weight]] ] = 0.01,[ [[Value]] ] = 1000,[ [[Level]] ] = 0,[ [[Apply]] ] = {244},},
{[ [[Type]] ] = [[TREASURE]],[ [[Specials]] ] = {245},[ [[Flags]] ] = {246},[ [[Level]] ] = 40,[ [[Name]] ] = [[wolf eye tattoos]],[ [[Weight]] ] = 0.01,[ [[Value]] ] = 5000,[ [[Worn]] ] = [[EYES]],[ [[Provides]] ] = {247},[ [[Apply]] ] = {248},},
{[ [[Dice]] ] = [[2D3]],[ [[Level]] ] = 1,[ [[Flags]] ] = {249},[ [[Worn]] ] = [[one-handed]],[ [[Name]] ] = [[a broken dragon's fist mace]],[ [[Weight]] ] = 1.4,[ [[Value]] ] = 1,[ [[AvgDmg]] ] = [[4.0]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {250},},
{[ [[Flags]] ] = {251},[ [[Type]] ] = [[TRASH]],[ [[Name]] ] = [[a ring of the 3rd Black Legion]],[ [[Weight]] ] = 0.02,[ [[Value]] ] = 0,[ [[Worn]] ] = [[FINGER]],[ [[Level]] ] = 8,},
{[ [[Type]] ] = [[STAFF]],[ [[Specials]] ] = {252},[ [[Flags]] ] = {253},[ [[Casts]] ] = {254},[ [[Name]] ] = [[a black and gold harp]],[ [[Weight]] ] = 3,[ [[Value]] ] = 0,[ [[Level]] ] = 70,[ [[Worn]] ] = [[HOLD OBELT]],[ [[Apply]] ] = {255},},
{[ [[Flags]] ] = {256},[ [[Type]] ] = [[POTION]],[ [[Name]] ] = [[a bottle of nostrum]],[ [[Weight]] ] = 0.3,[ [[Value]] ] = 8000,[ [[Level]] ] = 45,[ [[Casts]] ] = {257},},
{[ [[Flags]] ] = {258},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a bat tooth necklace]],[ [[Weight]] ] = 0.4,[ [[Value]] ] = 145,[ [[Worn]] ] = [[NECK]],[ [[Level]] ] = 5,[ [[Apply]] ] = {259},},
{[ [[Flags]] ] = {260},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[the Shield of Darkness]],[ [[Weight]] ] = 2,[ [[Value]] ] = 600,[ [[Worn]] ] = [[SHIELD]],[ [[Level]] ] = 40,[ [[Apply]] ] = {261},},
{[ [[Type]] ] = [[TREASURE]],[ [[Specials]] ] = {262},[ [[Flags]] ] = {263},[ [[Name]] ] = [[the jewel of the heart]],[ [[Weight]] ] = 0.2,[ [[Value]] ] = 1782,[ [[Worn]] ] = [[NECK]],[ [[Level]] ] = 5,[ [[Apply]] ] = {264},},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[ARMOR]] ] = [[0]],},
{[1] = [[!SORCERER]],[2] = [[!DRUID]],[3] = [[!NECROMANCER]],[4] = [[!CONJURER]],[5] = [[!MONK]],[6] = [[!THIEF]],[7] = [[!PYROMANCER]],[8] = [[!CRYOMANCER]],[9] = [[!ILLUSIONIST]],[10] = [[!PRIEST]],[11] = [[!DIABOLIST]],},
{[ [[ARMOR]] ] = [[5]],},
{[1] = [[!RENT]],},
{[1] = [[MAGIC]],[2] = [[!SORCERER]],[3] = [[!NECROMANCER]],[4] = [[!CONJURER]],[5] = [[!PYROMANCER]],[6] = [[!CRYOMANCER]],[7] = [[!ILLUSIONIST]],},
{[ [[DAMROLL]] ] = [[+3]],[ [[HITROLL]] ] = [[+3]],},
{[1] = [[!BERSERKER]],[2] = [[MAGIC]],[3] = [[!DROP]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!ROGUE]],[7] = [[!WARRIOR]],[8] = [[!SELL]],[9] = [[!PALADIN]],[10] = [[!ANTI_PALADIN]],[11] = [[!DRUID]],[12] = [[!SHAMAN]],[13] = [[!ASSASSIN]],[14] = [[!MERCENARY]],[15] = [[!NECROMANCER]],[16] = [[!CONJURER]],[20] = [[!PYROMANCER]],[17] = [[!MONK]],[21] = [[!CRYOMANCER]],[18] = [[!BARD]],[22] = [[!ILLUSIONIST]],[19] = [[!THIEF]],[23] = [[!PRIEST]],[24] = [[!DIABOLIST]],},
{[1] = [[!TRACK]],},
{[ [[MAXMOVE]] ] = [[+30]],[ [[HITROLL]] ] = [[+1]],[ [[DAMROLL]] ] = [[+2]],[ [[ARMOR]] ] = [[7]],},
{[1] = [[!SORCERER]],[2] = [[!CLERIC]],[3] = [[!DRUID]],[4] = [[!SHAMAN]],[5] = [[!NECROMANCER]],[6] = [[!CONJURER]],[7] = [[!MONK]],[8] = [[!PYROMANCER]],[9] = [[!CRYOMANCER]],[10] = [[!ILLUSIONIST]],[11] = [[!PRIEST]],[12] = [[!DIABOLIST]],},
{[ [[DAMROLL]] ] = [[+1]],},
{[1] = [[!EVIL]],[2] = [[!SORCERER]],[3] = [[!NECROMANCER]],[4] = [[!CONJURER]],[5] = [[!PYROMANCER]],[6] = [[!CRYOMANCER]],[7] = [[!ILLUSIONIST]],},
{[ [[ARMOR]] ] = [[13]],[ [[HITPOINTS]] ] = [[+5]],[ [[CON]] ] = [[+2]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[!EVIL]],[2] = [[!SORCERER]],[3] = [[!NECROMANCER]],[4] = [[!CONJURER]],[5] = [[!PYROMANCER]],[6] = [[!CRYOMANCER]],[7] = [[!ILLUSIONIST]],},
{[ [[ARMOR]] ] = [[6]],[ [[DEX]] ] = [[+2]],},
{[1] = [[MAGIC]],},
{[1] = [[remove poison]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[ARMOR]] ] = [[10]],[ [[HITROLL]] ] = [[+1]],[ [[DAMROLL]] ] = [[+1]],[ [[HITPOINTS]] ] = [[+15]],},
{[1] = [[baton_cone_of_cold]],},
{[1] = [[MAGIC]],[2] = [[!SORCERER]],[3] = [[!CLERIC]],[4] = [[!ROGUE]],[5] = [[!DRUID]],[6] = [[!SHAMAN]],[7] = [[!ASSASSIN]],[8] = [[!NECROMANCER]],[9] = [[!CONJURER]],[10] = [[!BURN]],[11] = [[!LOCATE]],[12] = [[FLOAT]],},
{[1] = [[HUM]],},
{[ [[HITPOINTS]] ] = [[+75]],[ [[HITROLL]] ] = [[+3]],[ [[ARMOR]] ] = [[3]],[ [[DAMROLL]] ] = [[+3]],},
{[1] = [[GLOW]],[2] = [[HUM]],},
{[1] = [[GLOW]],[2] = [[HUM]],},
{[ [[SAVING_BREATH]] ] = [[-2]],},
{[1] = [[!GOOD]],[2] = [[!SORCERER]],[3] = [[!PALADIN]],[4] = [[!RANGER]],[5] = [[!DRUID]],[6] = [[!NECROMANCER]],[7] = [[!CONJURER]],[8] = [[!MONK]],[9] = [[!PYROMANCER]],[10] = [[!CRYOMANCER]],[11] = [[!ILLUSIONIST]],[12] = [[!PRIEST]],},
{[ [[HITROLL]] ] = [[-2]],[ [[DAMROLL]] ] = [[+2]],[ [[CON]] ] = [[+3]],},
{[1] = [[!BERSERKER]],[2] = [[MAGIC]],[3] = [[!DROP]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!ROGUE]],[7] = [[!WARRIOR]],[8] = [[!SELL]],[9] = [[!PALADIN]],[10] = [[!ANTI_PALADIN]],[11] = [[!DRUID]],[12] = [[!SHAMAN]],[13] = [[!ASSASSIN]],[14] = [[!MERCENARY]],[15] = [[!NECROMANCER]],[16] = [[!CONJURER]],[20] = [[!PYROMANCER]],[17] = [[!MONK]],[21] = [[!CRYOMANCER]],[18] = [[!BARD]],[22] = [[!ILLUSIONIST]],[19] = [[!THIEF]],[23] = [[!PRIEST]],[24] = [[!DIABOLIST]],},
{[ [[DEX]] ] = [[+2]],[ [[STR]] ] = [[+3]],[ [[DAMROLL]] ] = [[+2]],[ [[ARMOR]] ] = [[35]],},
{[1] = [[GLOW]],},
{[1] = [[cure light]],[2] = [[cure light]],[3] = [[and cure light]],},
{[1] = [[FLOAT]],},
{[ [[CHA]] ] = [[+2]],[ [[ARMOR]] ] = [[3]],[ [[HITPOINTS]] ] = [[+3]],},
{[1] = [[FLOAT]],},
{[ [[INT]] ] = [[+1]],[ [[WIS]] ] = [[+1]],[ [[MAXMOVE]] ] = [[+15]],},
{[1] = [[HUM]],[2] = [[!BERSERKER]],[3] = [[!EVIL]],[4] = [[!SORCERER]],[5] = [[!WARRIOR]],[6] = [[!ANTI_PALADIN]],[7] = [[!RANGER]],[8] = [[!ASSASSIN]],[9] = [[!MERCENARY]],[10] = [[!NECROMANCER]],[11] = [[!BARD]],[12] = [[!PYROMANCER]],[13] = [[!CRYOMANCER]],[14] = [[!ILLUSIONIST]],},
{[ [[INT]] ] = [[+1]],[ [[WIS]] ] = [[+1]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[cure critic]],[2] = [[cure critic]],[3] = [[and cure critic]],},
{[1] = [[!SELL]],},
{[1] = [[GLOW]],[2] = [[MAGIC]],[3] = [[!GOOD]],[4] = [[!SELL]],[5] = [[!DRUID]],[6] = [[FLOAT]],},
{[ [[AGE]] ] = [[+5]],[ [[WIS]] ] = [[-2]],[ [[DEX]] ] = [[+2]],[ [[ARMOR]] ] = [[+2]],},
{[1] = [[!SORCERER]],[2] = [[!NECROMANCER]],[3] = [[!CONJURER]],[4] = [[!PYROMANCER]],[5] = [[!CRYOMANCER]],[6] = [[!ILLUSIONIST]],},
{[ [[INT]] ] = [[-2]],[ [[ARMOR]] ] = [[7]],[ [[CON]] ] = [[+2]],},
{[1] = [[MAGIC]],},
{[ [[HITROLL]] ] = [[+2]],[ [[ARMOR]] ] = [[1]],[ [[DAMROLL]] ] = [[+1]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[ARMOR]] ] = [[1]],[ [[DAMROLL]] ] = [[+2]],[ [[STR]] ] = [[+1]],[ [[CON]] ] = [[+1]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[MAGIC]],[2] = [[!SORCERER]],[3] = [[!DRUID]],[4] = [[!NECROMANCER]],[5] = [[!CONJURER]],[6] = [[!MONK]],[7] = [[!PYROMANCER]],[8] = [[!CRYOMANCER]],[9] = [[!ILLUSIONIST]],},
{[ [[WIS]] ] = [[+2]],},
{[1] = [[MAGIC]],},
{[ [[ARMOR]] ] = [[0]],},
{[1] = [[MAGIC]],[2] = [[FLOAT]],},
{[1] = [[identify]],},
{[1] = [[GLOW]],[2] = [[!EVIL]],[3] = [[!SORCERER]],[4] = [[!CLERIC]],[5] = [[!DRUID]],[6] = [[!SHAMAN]],[7] = [[!NECROMANCER]],[8] = [[!CONJURER]],[9] = [[!MONK]],[10] = [[ELVEN]],[11] = [[!PYROMANCER]],[12] = [[!CRYOMANCER]],[13] = [[!ILLUSIONIST]],[14] = [[!PRIEST]],[15] = [[!DIABOLIST]],},
{[ [[DAMROLL]] ] = [[+1]],},
{[1] = [[!EVIL]],[2] = [[!SORCERER]],[3] = [[!NECROMANCER]],[4] = [[!CONJURER]],[5] = [[!PYROMANCER]],[6] = [[!CRYOMANCER]],[7] = [[!ILLUSIONIST]],},
{[ [[ARMOR]] ] = [[7]],[ [[INT]] ] = [[+2]],},
{[1] = [[FLOAT]],},
{[ [[ARMOR]] ] = [[1]],[ [[HITPOINTS]] ] = [[+3]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[DET_INVIS]],[2] = [[FARSEE]],},
{[ [[WIS]] ] = [[+2]],[ [[ARMOR]] ] = [[0]],[ [[PERCEPTION]] ] = [[+150]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[HITROLL]] ] = [[+1]],[ [[HITPOINTS]] ] = [[+2]],[ [[ARMOR]] ] = [[0]],},
{[1] = [[GLOW]],[2] = [[MAGIC]],[3] = [[!EVIL]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!DRUID]],[7] = [[!NECROMANCER]],[8] = [[!CONJURER]],[9] = [[!MONK]],[10] = [[ELVEN]],[11] = [[!PYROMANCER]],[12] = [[!CRYOMANCER]],[13] = [[!ILLUSIONIST]],[14] = [[!PRIEST]],[15] = [[!DIABOLIST]],},
{[ [[STR]] ] = [[+1]],[ [[DAMROLL]] ] = [[+1]],},
{[1] = [[FLOAT]],},
{[1] = [[MAGIC]],[2] = [[!SELL]],[3] = [[FLOAT]],},
{[1] = [[recall]],},
{[1] = [[MAGIC]],[2] = [[!EVIL]],[3] = [[!SORCERER]],[4] = [[!ROGUE]],[5] = [[!DRUID]],[6] = [[!ASSASSIN]],[7] = [[!NECROMANCER]],[8] = [[!CONJURER]],[9] = [[!MONK]],[10] = [[!BARD]],[11] = [[!THIEF]],[12] = [[!PYROMANCER]],[13] = [[!CRYOMANCER]],[14] = [[!ILLUSIONIST]],[15] = [[!DIABOLIST]],},
{[ [[HITROLL]] ] = [[+1]],[ [[ARMOR]] ] = [[7]],[ [[DEX]] ] = [[+2]],},
{[1] = [[!BERSERKER]],[2] = [[MAGIC]],[3] = [[!DROP]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!ROGUE]],[7] = [[!WARRIOR]],[8] = [[!SELL]],[9] = [[!PALADIN]],[10] = [[!ANTI_PALADIN]],[11] = [[!DRUID]],[12] = [[!SHAMAN]],[13] = [[!ASSASSIN]],[14] = [[!MERCENARY]],[15] = [[!NECROMANCER]],[16] = [[!CONJURER]],[20] = [[!PYROMANCER]],[17] = [[!MONK]],[21] = [[!CRYOMANCER]],[18] = [[!BARD]],[22] = [[!ILLUSIONIST]],[19] = [[!THIEF]],[23] = [[!PRIEST]],[24] = [[!DIABOLIST]],},
{[ [[HITROLL]] ] = [[+2]],[ [[ARMOR]] ] = [[4]],[ [[DAMROLL]] ] = [[+1]],},
{[1] = [[!SELL]],[2] = [[FLOAT]],},
{[1] = [[FLOAT]],},
{[ [[STR]] ] = [[+2]],[ [[DAMROLL]] ] = [[+1]],[ [[ARMOR]] ] = [[3]],},
{[1] = [[!RENT]],},
{[1] = [[GLOW]],[2] = [[!BERSERKER]],[3] = [[MAGIC]],[4] = [[!DROP]],[5] = [[!SORCERER]],[6] = [[!CLERIC]],[7] = [[!ROGUE]],[8] = [[!WARRIOR]],[9] = [[!SELL]],[10] = [[!PALADIN]],[11] = [[!ANTI_PALADIN]],[12] = [[!DRUID]],[13] = [[!SHAMAN]],[14] = [[!ASSASSIN]],[15] = [[!MERCENARY]],[16] = [[!NECROMANCER]],[17] = [[!CONJURER]],[18] = [[FLOAT]],[19] = [[!MONK]],[20] = [[!BARD]],[21] = [[!THIEF]],[22] = [[!PYROMANCER]],[23] = [[!CRYOMANCER]],[24] = [[!ILLUSIONIST]],[25] = [[!PRIEST]],[26] = [[!DIABOLIST]],},
{[ [[WIS]] ] = [[+3]],[ [[STR]] ] = [[+2]],[ [[ARMOR]] ] = [[3]],},
{[1] = [[FLOAT]],},
{[ [[DEX]] ] = [[+1]],[ [[ARMOR]] ] = [[3]],[ [[CON]] ] = [[+3]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[!BERSERKER]],[2] = [[!EVIL]],[3] = [[!ROGUE]],[4] = [[!WARRIOR]],[5] = [[!ANTI_PALADIN]],[6] = [[!RANGER]],[7] = [[!ASSASSIN]],[8] = [[!MERCENARY]],[9] = [[!NECROMANCER]],[10] = [[!THIEF]],},
{[ [[ARMOR]] ] = [[7]],[ [[INT]] ] = [[+2]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[ARMOR]] ] = [[0]],},
{[1] = [[!EVIL]],[2] = [[!SORCERER]],[3] = [[!CLERIC]],[4] = [[!DRUID]],[5] = [[!SHAMAN]],[6] = [[!NECROMANCER]],[7] = [[!CONJURER]],[8] = [[!MONK]],[9] = [[ELVEN]],[10] = [[!PYROMANCER]],[11] = [[!CRYOMANCER]],[12] = [[!ILLUSIONIST]],[13] = [[!PRIEST]],[14] = [[!DIABOLIST]],},
{[1] = [[GLOW]],[2] = [[!BERSERKER]],[3] = [[MAGIC]],[4] = [[!DROP]],[5] = [[!SORCERER]],[6] = [[!CLERIC]],[7] = [[!ROGUE]],[8] = [[!WARRIOR]],[9] = [[!SELL]],[10] = [[!PALADIN]],[11] = [[!ANTI_PALADIN]],[12] = [[!DRUID]],[13] = [[!SHAMAN]],[14] = [[!ASSASSIN]],[15] = [[!MERCENARY]],[16] = [[!NECROMANCER]],[17] = [[!CONJURER]],[18] = [[FLOAT]],[19] = [[!MONK]],[20] = [[!BARD]],[21] = [[!THIEF]],[22] = [[!PYROMANCER]],[23] = [[!CRYOMANCER]],[24] = [[!ILLUSIONIST]],[25] = [[!PRIEST]],[26] = [[!DIABOLIST]],},
{[ [[HITPOINTS]] ] = [[+18]],[ [[ARMOR]] ] = [[13]],[ [[CON]] ] = [[+3]],},
{[1] = [[HUM]],[2] = [[!GOOD]],[3] = [[!NEUTRAL]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!NECROMANCER]],[7] = [[!CONJURER]],[8] = [[!MONK]],[9] = [[!PYROMANCER]],[10] = [[!CRYOMANCER]],[11] = [[!ILLUSIONIST]],[12] = [[!PRIEST]],[13] = [[!DIABOLIST]],},
{[ [[DAMROLL]] ] = [[+2]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[tempest of saint augustine]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[innate chaz]],[2] = [[enhance strength]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[MAGIC]],},
{[ [[ARMOR]] ] = [[2]],[ [[HITROLL]] ] = [[+2]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[CHA]] ] = [[+2]],[ [[ARMOR]] ] = [[0]],[ [[HITROLL]] ] = [[+1]],},
{[1] = [[!BERSERKER]],[2] = [[MAGIC]],[3] = [[!DROP]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!ROGUE]],[7] = [[!WARRIOR]],[8] = [[!SELL]],[9] = [[!PALADIN]],[10] = [[!ANTI_PALADIN]],[11] = [[!DRUID]],[12] = [[!SHAMAN]],[13] = [[!ASSASSIN]],[14] = [[!MERCENARY]],[15] = [[!NECROMANCER]],[16] = [[!CONJURER]],[20] = [[!PYROMANCER]],[17] = [[!MONK]],[21] = [[!CRYOMANCER]],[18] = [[!BARD]],[22] = [[!ILLUSIONIST]],[19] = [[!THIEF]],[23] = [[!PRIEST]],[24] = [[!DIABOLIST]],},
{[ [[INT]] ] = [[+2]],[ [[ARMOR]] ] = [[7]],[ [[HITROLL]] ] = [[+1]],[ [[DAMROLL]] ] = [[+1]],[ [[HITPOINTS]] ] = [[+25]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[ARMOR]] ] = [[0]],[ [[INT]] ] = [[+2]],},
{[1] = [[forage]],[2] = [[obj]],[3] = [[normalizer]],[4] = [[Ranger]],[5] = [[Trophy]],[6] = [[command]],[7] = [[forage]],[8] = [[Ranger]],[9] = [[trophy]],[10] = [[attack]],[11] = [[counter]],},
{[1] = [[!SORCERER]],[2] = [[!CLERIC]],[3] = [[!ROGUE]],[4] = [[!PALADIN]],[5] = [[!ANTI_PALADIN]],[6] = [[!DRUID]],[7] = [[!SHAMAN]],[8] = [[!ASSASSIN]],[9] = [[!NECROMANCER]],[10] = [[!CONJURER]],[11] = [[FLOAT]],[12] = [[!MONK]],[13] = [[!BARD]],[14] = [[!THIEF]],[15] = [[!PYROMANCER]],[16] = [[!CRYOMANCER]],[17] = [[!ILLUSIONIST]],[18] = [[!PRIEST]],[19] = [[!DIABOLIST]],},
{[1] = [[SENSE_LIFE]],},
{[ [[DAMROLL]] ] = [[+1]],[ [[HITROLL]] ] = [[+1]],[ [[ARMOR]] ] = [[1]],[ [[PERCEPTION]] ] = [[+60]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[ARMOR]] ] = [[1]],[ [[SAVING_SPELL]] ] = [[-1]],},
{[1] = [[GLOW]],[2] = [[MAGIC]],},
{[1] = [[GLOW]],[2] = [[MAGIC]],},
{[1] = [[forage]],[2] = [[obj]],[3] = [[normalizer]],[4] = [[Ranger]],[5] = [[Trophy]],[6] = [[command]],[7] = [[forage]],[8] = [[Ranger]],[9] = [[trophy]],[10] = [[attack]],[11] = [[counter]],},
{[1] = [[!SORCERER]],[2] = [[!CLERIC]],[3] = [[!ROGUE]],[4] = [[!PALADIN]],[5] = [[!ANTI_PALADIN]],[6] = [[!DRUID]],[7] = [[!SHAMAN]],[8] = [[!ASSASSIN]],[9] = [[!NECROMANCER]],[10] = [[!CONJURER]],[11] = [[FLOAT]],[12] = [[!MONK]],[13] = [[!BARD]],[14] = [[!THIEF]],[15] = [[!PYROMANCER]],[16] = [[!CRYOMANCER]],[17] = [[!ILLUSIONIST]],[18] = [[!PRIEST]],[19] = [[!DIABOLIST]],},
{[1] = [[SENSE_LIFE]],},
{[ [[DAMROLL]] ] = [[+1]],[ [[HITROLL]] ] = [[+1]],[ [[ARMOR]] ] = [[2]],[ [[PERCEPTION]] ] = [[+80]],},
{[1] = [[!SORCERER]],[2] = [[!CLERIC]],[3] = [[!ROGUE]],[4] = [[!DRUID]],[5] = [[!SHAMAN]],[6] = [[!ASSASSIN]],[7] = [[!NECROMANCER]],[8] = [[!CONJURER]],[9] = [[!MONK]],[10] = [[!BARD]],[11] = [[!THIEF]],[12] = [[!PYROMANCER]],[13] = [[!CRYOMANCER]],[14] = [[!ILLUSIONIST]],[15] = [[!PRIEST]],[16] = [[!DIABOLIST]],},
{[ [[CON]] ] = [[+2]],},
{[1] = [[MAGIC]],[2] = [[!SORCERER]],[3] = [[!CLERIC]],[4] = [[!ROGUE]],[5] = [[!DRUID]],[6] = [[!SHAMAN]],[7] = [[!ASSASSIN]],[8] = [[!MERCENARY]],[9] = [[!NECROMANCER]],[10] = [[!CONJURER]],[11] = [[!BARD]],[12] = [[!THIEF]],[13] = [[!PYROMANCER]],[14] = [[!CRYOMANCER]],[15] = [[!ILLUSIONIST]],[16] = [[!PRIEST]],[17] = [[!DIABOLIST]],},
{[ [[HITROLL]] ] = [[+1]],[ [[ARMOR]] ] = [[6]],[ [[HITPOINTS]] ] = [[+7]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[CON]] ] = [[+2]],},
{[1] = [[MAGIC]],[2] = [[!BURN]],[3] = [[FLOAT]],},
{[1] = [[!SORCERER]],[2] = [[!CLERIC]],[3] = [[!ROGUE]],[4] = [[!DRUID]],[5] = [[!ASSASSIN]],[6] = [[!NECROMANCER]],[7] = [[!CONJURER]],[8] = [[!MONK]],[9] = [[!BARD]],[10] = [[DWARVEN]],[11] = [[!THIEF]],[12] = [[!PYROMANCER]],[13] = [[!CRYOMANCER]],[14] = [[!ILLUSIONIST]],[15] = [[!PRIEST]],[16] = [[!DIABOLIST]],},
{[ [[DEX]] ] = [[-3]],[ [[HITROLL]] ] = [[+1]],[ [[STR]] ] = [[-2]],[ [[DAMROLL]] ] = [[+1]],},
{[1] = [[!EVIL]],},
{[ [[INT]] ] = [[+2]],[ [[WIS]] ] = [[+2]],[ [[ARMOR]] ] = [[5]],[ [[HITPOINTS]] ] = [[+5]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[ARMOR]] ] = [[1]],[ [[HITPOINTS]] ] = [[+12]],},
{[1] = [[GLOW]],},
{[1] = [[FARSEE]],},
{[ [[ARMOR]] ] = [[0]],[ [[DEX]] ] = [[+5]],},
{[1] = [[GLOW]],[2] = [[HUM]],[3] = [[!BERSERKER]],[4] = [[MAGIC]],[5] = [[!DROP]],[6] = [[!SORCERER]],[7] = [[!CLERIC]],[8] = [[!ROGUE]],[9] = [[!WARRIOR]],[10] = [[!SELL]],[11] = [[!PALADIN]],[12] = [[!ANTI_PALADIN]],[13] = [[!DRUID]],[14] = [[!SHAMAN]],[15] = [[!ASSASSIN]],[16] = [[!MERCENARY]],[17] = [[!NECROMANCER]],[18] = [[!CONJURER]],[19] = [[!MONK]],[20] = [[!BARD]],[21] = [[!THIEF]],[22] = [[!PYROMANCER]],[23] = [[!CRYOMANCER]],[24] = [[!ILLUSIONIST]],[25] = [[!PRIEST]],[26] = [[!DIABOLIST]],},
{[ [[INT]] ] = [[+3]],[ [[ARMOR]] ] = [[7]],[ [[DAMROLL]] ] = [[+1]],[ [[HITROLL]] ] = [[+2]],[ [[DEX]] ] = [[+2]],[ [[HITPOINTS]] ] = [[+25]],},
{[1] = [[!SORCERER]],[2] = [[!CLERIC]],[3] = [[!ROGUE]],[4] = [[!DRUID]],[5] = [[!SHAMAN]],[6] = [[!ASSASSIN]],[7] = [[!NECROMANCER]],[8] = [[!CONJURER]],[9] = [[!MONK]],[10] = [[!BARD]],[11] = [[!THIEF]],[12] = [[!PYROMANCER]],[13] = [[!CRYOMANCER]],[14] = [[!ILLUSIONIST]],[15] = [[!PRIEST]],[16] = [[!DIABOLIST]],},
{[ [[CHA]] ] = [[+3]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[invisibility]],[2] = [[protection from air]],},
{[1] = [[!BERSERKER]],[2] = [[MAGIC]],[3] = [[!DROP]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!ROGUE]],[7] = [[!WARRIOR]],[8] = [[!SELL]],[9] = [[!PALADIN]],[10] = [[!ANTI_PALADIN]],[11] = [[!DRUID]],[12] = [[!SHAMAN]],[13] = [[!ASSASSIN]],[14] = [[!MERCENARY]],[15] = [[!NECROMANCER]],[16] = [[!CONJURER]],[20] = [[!PYROMANCER]],[17] = [[!MONK]],[21] = [[!CRYOMANCER]],[18] = [[!BARD]],[22] = [[!ILLUSIONIST]],[19] = [[!THIEF]],[23] = [[!PRIEST]],},
{[1] = [[DET_INVIS]],},
{[ [[HITROLL]] ] = [[+1]],[ [[ARMOR]] ] = [[5]],[ [[DAMROLL]] ] = [[+2]],},
{[1] = [[FLOAT]],[2] = [[!FALL]],},
{[ [[INT]] ] = [[+2]],[ [[WIS]] ] = [[+2]],[ [[ARMOR]] ] = [[+4]],[ [[CHAR_HEIGHT]] ] = [[+5]],},
{[1] = [[!BERSERKER]],[2] = [[MAGIC]],[3] = [[!DROP]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!ROGUE]],[7] = [[!WARRIOR]],[8] = [[!SELL]],[9] = [[!PALADIN]],[10] = [[!ANTI_PALADIN]],[11] = [[!DRUID]],[12] = [[!SHAMAN]],[13] = [[!ASSASSIN]],[14] = [[!MERCENARY]],[15] = [[!NECROMANCER]],[16] = [[!CONJURER]],[20] = [[!PYROMANCER]],[17] = [[!MONK]],[21] = [[!CRYOMANCER]],[18] = [[!BARD]],[22] = [[!ILLUSIONIST]],[19] = [[!THIEF]],[23] = [[!PRIEST]],[24] = [[!DIABOLIST]],},
{[ [[DAMROLL]] ] = [[+1]],[ [[HITROLL]] ] = [[+2]],[ [[DEX]] ] = [[+2]],[ [[ARMOR]] ] = [[3]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[ARMOR]] ] = [[0]],},
{[1] = [[forage]],[2] = [[obj]],[3] = [[normalizer]],[4] = [[Ranger]],[5] = [[Trophy]],[6] = [[command]],[7] = [[forage]],[8] = [[Ranger]],[9] = [[trophy]],[10] = [[attack]],[11] = [[counter]],},
{[1] = [[!SORCERER]],[2] = [[!CLERIC]],[3] = [[!ROGUE]],[4] = [[!PALADIN]],[5] = [[!ANTI_PALADIN]],[6] = [[!DRUID]],[7] = [[!SHAMAN]],[8] = [[!ASSASSIN]],[9] = [[!NECROMANCER]],[10] = [[!CONJURER]],[11] = [[FLOAT]],[12] = [[!MONK]],[13] = [[!BARD]],[14] = [[!THIEF]],[15] = [[!PYROMANCER]],[16] = [[!CRYOMANCER]],[17] = [[!ILLUSIONIST]],[18] = [[!PRIEST]],[19] = [[!DIABOLIST]],},
{[1] = [[SENSE_LIFE]],[2] = [[FARSEE]],},
{[ [[DAMROLL]] ] = [[+1]],[ [[HITROLL]] ] = [[+1]],[ [[ARMOR]] ] = [[2]],[ [[PERCEPTION]] ] = [[+100]],},
{[1] = [[MAGIC]],[2] = [[!SORCERER]],[3] = [[!NECROMANCER]],[4] = [[!CONJURER]],},
{[ [[CON]] ] = [[+1]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[charm_person_instruments_command]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[chain lightning]],},
{[ [[HITPOINTS]] ] = [[+25]],[ [[CHA]] ] = [[+5]],[ [[ARMOR]] ] = [[+1]],[ [[HITROLL]] ] = [[+3]],},
{[1] = [[MAGIC]],},
{[1] = [[cure critic]],},
{[1] = [[MAGIC]],},
{[ [[HITROLL]] ] = [[+1]],[ [[HITPOINTS]] ] = [[+10]],[ [[ARMOR]] ] = [[1]],},
{[1] = [[MAGIC]],[2] = [[!GOOD]],},
{[ [[ARMOR]] ] = [[11]],[ [[HITROLL]] ] = [[+3]],},
{[1] = [[quest_ranger_druid_subclass_heart_limiter]],},
{[1] = [[GLOW]],},
{[ [[ARMOR]] ] = [[0]],[ [[HITPOINTS]] ] = [[+20]],},
}
