return {{[ [[a flawed agate]] ] = {2},[ [[a kuwagata]] ] = {3},[ [[a runestone]] ] = {4},[ [[a dragon's fist mace]] ] = {5},[ [[a leather bag]] ] = {6},[ [[Boots of the Protector]] ] = {7},[ [[a steel battle-axe]] ] = {8},[ [[a leather jerkin of the 3rd Eldorian Guard]] ] = {9},[ [[a token of the 3rd Black Legion]] ] = {10},[ [[boots of the 3rd Eldorian Guard]] ] = {11},[ [[a clear potion of remove poison]] ] = {12},[ [[a leather water skin]] ] = {13},[ [[a Fiery Red drakling scale]] ] = {14},[ [[a lightweight baton]] ] = {15},[ [[Woodsmen Embroidered Leather Jerkin]] ] = {16},[ [[a crystal ring]] ] = {17},[ [[a speckled egg]] ] = {18},[ [[the Shadow Lance]] ] = {19},[ [[the Book of Redemption]] ] = {20},[ [[a tundra cloak]] ] = {21},[ [[Tunic of the Protector]] ] = {22},[ [[a small potion]] ] = {23},[ [[the Fire Goddess's skirt]] ] = {24},[ [[the Xapizan Codex]] ] = {25},[ [[a radiant dagger]] ] = {26},[ [[a vial of sparks]] ] = {27},[ [[a dark potion]] ] = {28},[ [[rosary beads]] ] = {29},[ [[a cloth sack]] ] = {30},[ [[a Chaos orb]] ] = {31},[ [[a bark canoe]] ] = {32},[ [[a bracelet with boar images on it]] ] = {33},[ [[a stone necklace]] ] = {34},[ [[a pair of Stryker's gloves]] ] = {35},[ [[Crest of the Dragon Hunter]] ] = {36},[ [[a granite ring]] ] = {37},[ [[a maul]] ] = {38},[ [[a spyglass]] ] = {39},[ [[the Spirit of the Great Beast]] ] = {40},[ [[a dwarven mallet]] ] = {41},[ [[a scroll of identify]] ] = {42},[ [[a blue vial]] ] = {43},[ [[a golden robe]] ] = {44},[ [[fur trimmed hide bracers]] ] = {45},[ [[a black flame]] ] = {46},[ [[the Kinship Broadsword]] ] = {47},[ [[a dark cloak]] ] = {48},[ [[leggings of the 3rd Eldorian Guard]] ] = {49},[ [[a jeweled leopard's eye]] ] = {50},[ [[a ceramic green spider]] ] = {51},[ [[the Snow Leopard Cloak]] ] = {52},[ [[a grey cloth shirt]] ] = {53},[ [[an octant]] ] = {54},[ [[Leggings of the Protector]] ] = {55},[ [[a seashell shard]] ] = {56},[ [[a handful of rubies]] ] = {57},[ [[some cheese]] ] = {58},[ [[an iridescent sword]] ] = {59},[ [[a diamond engagement ring]] ] = {60},[ [[a bird wing tattoo]] ] = {61},[ [[a crocodile-tooth necklace]] ] = {62},[ [[Sleeves of the Protector]] ] = {63},[ [[a spellbook]] ] = {64},[ [[a zebra skin cloak]] ] = {65},[ [[a skull of the 3rd Eldorian Guard]] ] = {66},[ [[Woodsmen Bracer]] ] = {67},[ [[a wolf fur cloak]] ] = {68},[ [[a badge of the 3rd Black Legion]] ] = {69},[ [[a vial of unholy water]] ] = {70},[ [[the Flail of Yeenoghu]] ] = {71},[ [[a gray scroll of recall]] ] = {72},[ [[a longsword of the 3rd Eldorian Guard]] ] = {73},[ [[a vulture feather]] ] = {74},[ [[a robe of the 3rd Eldorian Guard]] ] = {75},[ [[a shoot of thyme]] ] = {76},[ [[a monocle]] ] = {77},[ [[Helm of the Protector]] ] = {78},[ [[a striking jade necklace]] ] = {79},[ [[a citrine shard]] ] = {80},[ [[a thin sheet of cloud]] ] = {81},[ [[a bluish-silver helm]] ] = {82},[ [[Studded Gauntlets of the Protector]] ] = {83},[ [[a thin copper bracelet]] ] = {84},[ [[an ornamental christmas ball]] ] = {85},[ [[a legendary ice fang]] ] = {86},[ [[a jagged greataxe]] ] = {87},[ [[trainee greaves]] ] = {88},[ [[a leather saddle]] ] = {89},[ [[a black leather bag]] ] = {90},[ [[a wand of the 3rd Black Legion]] ] = {91},[ [[a bear claw tattoo]] ] = {92},[ [[the Shield of Darkness]] ] = {93},[ [[a skull of the 3rd Black Legion]] ] = {94},[ [[a dwarven war axe]] ] = {95},[ [[an alabaster-pommelled broadsword]] ] = {96},[ [[a clear vial]] ] = {97},[ [[the Nightblade]] ] = {98},[ [[a pale circlet]] ] = {99},[ [[Bracer of the Protector]] ] = {100},[ [[a crushed aquamarine]] ] = {101},[ [[wolf eye tattoos]] ] = {102},[ [[a broken dragon's fist mace]] ] = {103},[ [[a ring of the 3rd Black Legion]] ] = {104},[ [[a black and gold harp]] ] = {105},[ [[a bottle of nostrum]] ] = {106},[ [[a bat tooth necklace]] ] = {107},[ [[the aspen key]] ] = {108},[ [[the jewel of the heart]] ] = {109},},
{[ [[Flags]] ] = {110},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a flawed agate]],[ [[Weight]] ] = 0.01,[ [[Value]] ] = 4000,[ [[Level]] ] = 0,[ [[Apply]] ] = {111},},
{[ [[Flags]] ] = {112},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a kuwagata]],[ [[Weight]] ] = 2,[ [[Value]] ] = 750,[ [[Worn]] ] = [[HEAD]],[ [[Level]] ] = 20,[ [[Apply]] ] = {113},},
{[ [[Flags]] ] = {114},[ [[Type]] ] = [[KEY]],[ [[Name]] ] = [[a runestone]],[ [[Weight]] ] = 0.75,[ [[Value]] ] = 0,[ [[Level]] ] = 0,},
{[ [[Dice]] ] = [[4D4]],[ [[Worn]] ] = [[one-handed]],[ [[Flags]] ] = {115},[ [[AvgDmg]] ] = [[10.0]],[ [[Name]] ] = [[a dragon's fist mace]],[ [[Weight]] ] = 7,[ [[Value]] ] = 2000,[ [[Level]] ] = 60,[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {116},},
{[ [[Flags]] ] = {117},[ [[Type]] ] = [[CONTAINER]],[ [[Name]] ] = [[a leather bag]],[ [[Weight]] ] = 2,[ [[Value]] ] = 10,[ [[Level]] ] = 1,[ [[Reduction]] ] = [[0%]],[ [[Capacity]] ] = [[30]],},
{[ [[Type]] ] = [[ARMOR]],[ [[Flags]] ] = {118},[ [[Worn]] ] = [[FEET]],[ [[Name]] ] = [[Boots of the Protector]],[ [[Weight]] ] = 3.57,[ [[Value]] ] = 0,[ [[Level]] ] = 41,[ [[Provides]] ] = {119},[ [[Apply]] ] = {120},},
{[ [[Dice]] ] = [[2D6]],[ [[Worn]] ] = [[one-handed]],[ [[Flags]] ] = {121},[ [[AvgDmg]] ] = [[7.0]],[ [[Name]] ] = [[a steel battle-axe]],[ [[Weight]] ] = 5,[ [[Value]] ] = 500,[ [[Level]] ] = 35,[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {122},},
{[ [[Flags]] ] = {123},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a leather jerkin of the 3rd Eldorian Guard]],[ [[Weight]] ] = 8,[ [[Value]] ] = 0,[ [[Worn]] ] = [[BODY]],[ [[Level]] ] = 12,[ [[Apply]] ] = {124},},
{[ [[Flags]] ] = {125},[ [[Type]] ] = [[TRASH]],[ [[Name]] ] = [[a token of the 3rd Black Legion]],[ [[Weight]] ] = 1,[ [[Value]] ] = 0,[ [[Level]] ] = 8,},
{[ [[Flags]] ] = {126},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[boots of the 3rd Eldorian Guard]],[ [[Weight]] ] = 2.3,[ [[Value]] ] = 0,[ [[Worn]] ] = [[FEET]],[ [[Level]] ] = 12,[ [[Apply]] ] = {127},},
{[ [[Flags]] ] = {128},[ [[Type]] ] = [[POTION]],[ [[Name]] ] = [[a clear potion of remove poison]],[ [[Weight]] ] = 0.15,[ [[Value]] ] = 500,[ [[Level]] ] = 1,[ [[Casts]] ] = {129},},
{[ [[Type]] ] = [[LIQCONTAINER]],[ [[LiquidCapacity]] ] = [[256]],[ [[Flags]] ] = {130},[ [[Name]] ] = [[a leather water skin]],[ [[Weight]] ] = 2,[ [[Value]] ] = 10,[ [[Level]] ] = 1,[ [[Liquid]] ] = [[water]],[ [[Worn]] ] = [[HOLD]],},
{[ [[Flags]] ] = {131},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a Fiery Red drakling scale]],[ [[Weight]] ] = 0.5,[ [[Value]] ] = 0,[ [[Worn]] ] = [[BADGE]],[ [[Level]] ] = 1,[ [[Apply]] ] = {132},},
{[ [[Dice]] ] = [[3D6]],[ [[Specials]] ] = {133},[ [[Flags]] ] = {134},[ [[Level]] ] = 90,[ [[Name]] ] = [[a lightweight baton]],[ [[Weight]] ] = 2.4,[ [[Value]] ] = 34902,[ [[AvgDmg]] ] = [[10.5]],[ [[Type]] ] = [[WEAPON]],[ [[Worn]] ] = [[one-handed]],},
{[ [[Flags]] ] = {135},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[Woodsmen Embroidered Leather Jerkin]],[ [[Weight]] ] = 8,[ [[Value]] ] = 0,[ [[Worn]] ] = [[BODY]],[ [[Level]] ] = 21,[ [[Apply]] ] = {136},},
{[ [[Flags]] ] = {137},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a crystal ring]],[ [[Weight]] ] = 0.02,[ [[Value]] ] = 1200,[ [[Worn]] ] = [[FINGER]],[ [[Level]] ] = 50,[ [[Apply]] ] = {138},},
{[ [[Type]] ] = [[CONTAINER]],[ [[Is]] ] = {139},[ [[Reduction]] ] = [[0%]],[ [[Flags]] ] = {140},[ [[Worn]] ] = [[HOLD]],[ [[Name]] ] = [[a speckled egg]],[ [[Weight]] ] = 0.2,[ [[Value]] ] = 0,[ [[Level]] ] = 5,[ [[Capacity]] ] = [[20]],[ [[Apply]] ] = {141},},
{[ [[Dice]] ] = [[4D2]],[ [[Level]] ] = 20,[ [[Flags]] ] = {142},[ [[Worn]] ] = [[one-handed]],[ [[Name]] ] = [[the Shadow Lance]],[ [[Weight]] ] = 3,[ [[Value]] ] = 200,[ [[AvgDmg]] ] = [[6.0]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {143},},
{[ [[Flags]] ] = {144},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[the Book of Redemption]],[ [[Weight]] ] = 1.1,[ [[Value]] ] = 0,[ [[Worn]] ] = [[HOLD]],[ [[Level]] ] = 45,[ [[Apply]] ] = {145},},
{[ [[Flags]] ] = {146},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a tundra cloak]],[ [[Weight]] ] = 8,[ [[Value]] ] = 5000,[ [[Worn]] ] = [[ABOUT]],[ [[Level]] ] = 25,[ [[Apply]] ] = {147},},
{[ [[Flags]] ] = {148},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[Tunic of the Protector]],[ [[Weight]] ] = 9.3,[ [[Value]] ] = 0,[ [[Worn]] ] = [[BODY]],[ [[Level]] ] = 41,[ [[Apply]] ] = {149},},
{[ [[Flags]] ] = {150},[ [[Type]] ] = [[POTION]],[ [[Name]] ] = [[a small potion]],[ [[Weight]] ] = 0.1,[ [[Value]] ] = 10,[ [[Level]] ] = 17,[ [[Casts]] ] = {151},},
{[ [[Flags]] ] = {152},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[the Fire Goddess's skirt]],[ [[Weight]] ] = 2,[ [[Value]] ] = 10000,[ [[Worn]] ] = [[WAIST]],[ [[Level]] ] = 5,[ [[Apply]] ] = {153},},
{[ [[Flags]] ] = {154},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[the Xapizan Codex]],[ [[Weight]] ] = 4,[ [[Value]] ] = 3000,[ [[Worn]] ] = [[HOLD]],[ [[Level]] ] = 35,[ [[Apply]] ] = {155},},
{[ [[Dice]] ] = [[5D2]],[ [[AvgDmg]] ] = [[7.5]],[ [[Flags]] ] = {156},[ [[Level]] ] = 30,[ [[Name]] ] = [[a radiant dagger]],[ [[Weight]] ] = 0.5,[ [[Value]] ] = 600,[ [[Worn]] ] = [[one-handed]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {157},},
{[ [[Flags]] ] = {158},[ [[Type]] ] = [[POTION]],[ [[Name]] ] = [[a vial of sparks]],[ [[Weight]] ] = 0,[ [[Value]] ] = 100,[ [[Level]] ] = 5,[ [[Casts]] ] = {159},},
{[ [[Flags]] ] = {160},[ [[Type]] ] = [[POTION]],[ [[Name]] ] = [[a dark potion]],[ [[Weight]] ] = 0.1,[ [[Value]] ] = 10,[ [[Level]] ] = 17,[ [[Casts]] ] = {161},},
{[ [[Flags]] ] = {162},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[rosary beads]],[ [[Weight]] ] = 0.2,[ [[Value]] ] = 100,[ [[Worn]] ] = [[HOLD]],[ [[Level]] ] = 10,[ [[Apply]] ] = {163},},
{[ [[Type]] ] = [[CONTAINER]],[ [[Capacity]] ] = [[60]],[ [[Reduction]] ] = [[0%]],[ [[Flags]] ] = {164},[ [[Name]] ] = [[a cloth sack]],[ [[Weight]] ] = 0.6,[ [[Value]] ] = 1,[ [[Level]] ] = 1,[ [[Worn]] ] = [[HOLD OBELT]],},
{[ [[Type]] ] = [[LIGHT]],[ [[Flags]] ] = {165},[ [[Hours]] ] = [[Infinate]],[ [[Name]] ] = [[a Chaos orb]],[ [[Weight]] ] = 2,[ [[Value]] ] = 0,[ [[Level]] ] = 65,[ [[Worn]] ] = [[HOLD HOVER]],[ [[Apply]] ] = {166},},
{[ [[Flags]] ] = {167},[ [[Type]] ] = [[BOAT]],[ [[Name]] ] = [[a bark canoe]],[ [[Weight]] ] = 20,[ [[Value]] ] = 1,[ [[Worn]] ] = [[HOLD]],[ [[Level]] ] = 10,},
{[ [[Flags]] ] = {168},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a bracelet with boar images on it]],[ [[Weight]] ] = 0.25,[ [[Value]] ] = 0,[ [[Worn]] ] = [[WRIST]],[ [[Level]] ] = 5,[ [[Apply]] ] = {169},},
{[ [[Flags]] ] = {170},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a stone necklace]],[ [[Weight]] ] = 0.8,[ [[Value]] ] = 40,[ [[Worn]] ] = [[NECK WRIST]],[ [[Level]] ] = 35,[ [[Apply]] ] = {171},},
{[ [[Flags]] ] = {172},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a pair of Stryker's gloves]],[ [[Weight]] ] = 1.1,[ [[Value]] ] = 0,[ [[Worn]] ] = [[HANDS]],[ [[Level]] ] = 70,[ [[Apply]] ] = {173},},
{[ [[Type]] ] = [[TREASURE]],[ [[Flags]] ] = {174},[ [[Worn]] ] = [[BADGE]],[ [[Name]] ] = [[Crest of the Dragon Hunter]],[ [[Weight]] ] = 1,[ [[Value]] ] = 0,[ [[Level]] ] = 80,[ [[Provides]] ] = {175},[ [[Apply]] ] = {176},},
{[ [[Flags]] ] = {177},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a granite ring]],[ [[Weight]] ] = 0.04,[ [[Value]] ] = 450,[ [[Worn]] ] = [[FINGER]],[ [[Level]] ] = 45,[ [[Apply]] ] = {178},},
{[ [[Dice]] ] = [[4D2]],[ [[Level]] ] = 15,[ [[Flags]] ] = {179},[ [[Worn]] ] = [[one-handed]],[ [[Name]] ] = [[a maul]],[ [[Weight]] ] = 6.5,[ [[Value]] ] = 400,[ [[AvgDmg]] ] = [[6.0]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {180},},
{[ [[Type]] ] = [[TREASURE]],[ [[Flags]] ] = {181},[ [[Worn]] ] = [[HOLD]],[ [[Name]] ] = [[a spyglass]],[ [[Weight]] ] = 0.75,[ [[Value]] ] = 2000,[ [[Level]] ] = 10,[ [[Provides]] ] = {182},[ [[Apply]] ] = {183},},
{[ [[Type]] ] = [[TREASURE]],[ [[Flags]] ] = {184},[ [[Worn]] ] = [[EYES]],[ [[Name]] ] = [[the Spirit of the Great Beast]],[ [[Weight]] ] = 0.01,[ [[Value]] ] = 10000,[ [[Level]] ] = 90,[ [[Provides]] ] = {185},[ [[Apply]] ] = {186},},
{[ [[Dice]] ] = [[7D3]],[ [[AvgDmg]] ] = [[14.0]],[ [[Flags]] ] = {187},[ [[Level]] ] = 90,[ [[Name]] ] = [[a dwarven mallet]],[ [[Weight]] ] = 12.3,[ [[Value]] ] = 200,[ [[Worn]] ] = [[one-handed]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {188},},
{[ [[Flags]] ] = {189},[ [[Type]] ] = [[SCROLL]],[ [[Name]] ] = [[a scroll of identify]],[ [[Weight]] ] = 0.1,[ [[Value]] ] = 1,[ [[Worn]] ] = [[HOLD]],[ [[Casts]] ] = {190},[ [[Level]] ] = 1,},
{[ [[Flags]] ] = {191},[ [[Type]] ] = [[POTION]],[ [[Name]] ] = [[a blue vial]],[ [[Weight]] ] = 0.1,[ [[Value]] ] = 10,[ [[Level]] ] = 17,[ [[Casts]] ] = {192},},
{[ [[Flags]] ] = {193},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a golden robe]],[ [[Weight]] ] = 3,[ [[Value]] ] = 500,[ [[Worn]] ] = [[BODY]],[ [[Level]] ] = 30,[ [[Apply]] ] = {194},},
{[ [[Flags]] ] = {195},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[fur trimmed hide bracers]],[ [[Weight]] ] = 3.7,[ [[Value]] ] = 500,[ [[Worn]] ] = [[ARMS]],[ [[Level]] ] = 30,[ [[Apply]] ] = {196},},
{[ [[Type]] ] = [[LIGHT]],[ [[Specials]] ] = {197},[ [[Flags]] ] = {198},[ [[Level]] ] = 10,[ [[Name]] ] = [[a black flame]],[ [[Weight]] ] = 0,[ [[Value]] ] = 0,[ [[Hours]] ] = [[400]],[ [[Worn]] ] = [[HOLD HOVER]],[ [[Apply]] ] = {199},},
{[ [[Dice]] ] = [[3D4]],[ [[Worn]] ] = [[one-handed]],[ [[Flags]] ] = {200},[ [[AvgDmg]] ] = [[7.5]],[ [[Name]] ] = [[the Kinship Broadsword]],[ [[Weight]] ] = 5,[ [[Value]] ] = 1500,[ [[Level]] ] = 35,[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {201},},
{[ [[Flags]] ] = {202},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a dark cloak]],[ [[Weight]] ] = 3,[ [[Value]] ] = 200,[ [[Worn]] ] = [[ABOUT]],[ [[Level]] ] = 20,[ [[Apply]] ] = {203},},
{[ [[Flags]] ] = {204},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[leggings of the 3rd Eldorian Guard]],[ [[Weight]] ] = 4.9,[ [[Value]] ] = 0,[ [[Worn]] ] = [[LEGS]],[ [[Level]] ] = 12,[ [[Apply]] ] = {205},},
{[ [[Flags]] ] = {206},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a jeweled leopard's eye]],[ [[Weight]] ] = 0.25,[ [[Value]] ] = 2400,[ [[Worn]] ] = [[EYES]],[ [[Level]] ] = 45,[ [[Apply]] ] = {207},},
{[ [[Flags]] ] = {208},[ [[Type]] ] = [[WAND]],[ [[Name]] ] = [[a ceramic green spider]],[ [[Weight]] ] = 1.8,[ [[Value]] ] = 125,[ [[Worn]] ] = [[HOLD]],[ [[Casts]] ] = {209},[ [[Level]] ] = 70,},
{[ [[Type]] ] = [[ARMOR]],[ [[Specials]] ] = {210},[ [[Flags]] ] = {211},[ [[Name]] ] = [[the Snow Leopard Cloak]],[ [[Weight]] ] = 2.1,[ [[Value]] ] = 5900,[ [[Worn]] ] = [[ABOUT]],[ [[Level]] ] = 55,[ [[Apply]] ] = {212},},
{[ [[Flags]] ] = {213},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a grey cloth shirt]],[ [[Weight]] ] = 0.6,[ [[Value]] ] = 0,[ [[Worn]] ] = [[BODY]],[ [[Level]] ] = 1,[ [[Apply]] ] = {214},},
{[ [[Flags]] ] = {215},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[an octant]],[ [[Weight]] ] = 0.4,[ [[Value]] ] = 0,[ [[Worn]] ] = [[OBELT]],[ [[Level]] ] = 20,[ [[Apply]] ] = {216},},
{[ [[Flags]] ] = {217},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[Leggings of the Protector]],[ [[Weight]] ] = 8.6,[ [[Value]] ] = 0,[ [[Worn]] ] = [[LEGS]],[ [[Level]] ] = 41,[ [[Apply]] ] = {218},},
{[ [[Flags]] ] = {219},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a seashell shard]],[ [[Weight]] ] = 0.4,[ [[Value]] ] = 15,[ [[Worn]] ] = [[HOLD]],[ [[Level]] ] = 5,[ [[Apply]] ] = {220},},
{[ [[Flags]] ] = {221},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a handful of rubies]],[ [[Weight]] ] = 2,[ [[Value]] ] = 2000,[ [[Worn]] ] = [[HOLD]],[ [[Level]] ] = 1,[ [[Apply]] ] = {222},},
{[ [[Flags]] ] = {223},[ [[Type]] ] = [[FOOD]],[ [[Name]] ] = [[some cheese]],[ [[Weight]] ] = 0.8,[ [[Value]] ] = 5,[ [[Level]] ] = 1,[ [[Fillingness]] ] = [[8]],},
{[ [[Dice]] ] = [[2D8]],[ [[AvgDmg]] ] = [[9.0]],[ [[Flags]] ] = {224},[ [[Level]] ] = 35,[ [[Name]] ] = [[an iridescent sword]],[ [[Weight]] ] = 3,[ [[Value]] ] = 3000,[ [[Worn]] ] = [[one-handed]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {225},},
{[ [[Flags]] ] = {226},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a diamond engagement ring]],[ [[Weight]] ] = 0.02,[ [[Value]] ] = 18000,[ [[Worn]] ] = [[FINGER]],[ [[Level]] ] = 1,[ [[Apply]] ] = {227},},
{[ [[Type]] ] = [[TREASURE]],[ [[Specials]] ] = {228},[ [[Flags]] ] = {229},[ [[Level]] ] = 30,[ [[Name]] ] = [[a bird wing tattoo]],[ [[Weight]] ] = 0.01,[ [[Value]] ] = 4000,[ [[Worn]] ] = [[EYES]],[ [[Provides]] ] = {230},[ [[Apply]] ] = {231},},
{[ [[Flags]] ] = {232},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a crocodile-tooth necklace]],[ [[Weight]] ] = 1.2,[ [[Value]] ] = 0,[ [[Worn]] ] = [[NECK]],[ [[Level]] ] = 15,[ [[Apply]] ] = {233},},
{[ [[Flags]] ] = {234},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[Sleeves of the Protector]],[ [[Weight]] ] = 6.7,[ [[Value]] ] = 0,[ [[Worn]] ] = [[ARMS]],[ [[Level]] ] = 41,[ [[Apply]] ] = {235},},
{[ [[Flags]] ] = {236},[ [[Type]] ] = [[SPELLBOOK]],[ [[Name]] ] = [[a spellbook]],[ [[Weight]] ] = 2.5,[ [[Value]] ] = 1,[ [[Worn]] ] = [[HOLD]],[ [[Level]] ] = 1,},
{[ [[Flags]] ] = {237},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a zebra skin cloak]],[ [[Weight]] ] = 5,[ [[Value]] ] = 0,[ [[Worn]] ] = [[ABOUT]],[ [[Level]] ] = 15,[ [[Apply]] ] = {238},},
{[ [[Flags]] ] = {239},[ [[Type]] ] = [[TRASH]],[ [[Name]] ] = [[a skull of the 3rd Eldorian Guard]],[ [[Weight]] ] = 2.2,[ [[Value]] ] = 0,[ [[Level]] ] = 8,},
{[ [[Flags]] ] = {240},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[Woodsmen Bracer]],[ [[Weight]] ] = 0.64,[ [[Value]] ] = 0,[ [[Worn]] ] = [[WRIST]],[ [[Level]] ] = 21,[ [[Apply]] ] = {241},},
{[ [[Flags]] ] = {242},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a wolf fur cloak]],[ [[Weight]] ] = 5,[ [[Value]] ] = 200,[ [[Worn]] ] = [[ABOUT]],[ [[Level]] ] = 15,[ [[Apply]] ] = {243},},
{[ [[Flags]] ] = {244},[ [[Type]] ] = [[TRASH]],[ [[Name]] ] = [[a badge of the 3rd Black Legion]],[ [[Weight]] ] = 0.09,[ [[Value]] ] = 0,[ [[Worn]] ] = [[BADGE]],[ [[Level]] ] = 8,},
{[ [[Flags]] ] = {245},[ [[Type]] ] = [[POTION]],[ [[Name]] ] = [[a vial of unholy water]],[ [[Weight]] ] = 0.01,[ [[Value]] ] = 500,[ [[Level]] ] = 10,[ [[Casts]] ] = {246},},
{[ [[Dice]] ] = [[4D2]],[ [[AvgDmg]] ] = [[6.0]],[ [[Flags]] ] = {247},[ [[Level]] ] = 25,[ [[Name]] ] = [[the Flail of Yeenoghu]],[ [[Weight]] ] = 12,[ [[Value]] ] = 500,[ [[Worn]] ] = [[one-handed]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {248},},
{[ [[Flags]] ] = {249},[ [[Type]] ] = [[SCROLL]],[ [[Name]] ] = [[a gray scroll of recall]],[ [[Weight]] ] = 0.12,[ [[Value]] ] = 3000,[ [[Worn]] ] = [[HOLD]],[ [[Casts]] ] = {250},[ [[Level]] ] = 1,},
{[ [[Type]] ] = [[WEAPON]],[ [[Flags]] ] = {251},[ [[Level]] ] = 12,[ [[Name]] ] = [[a longsword of the 3rd Eldorian Guard]],[ [[Weight]] ] = 3,[ [[Value]] ] = 0,[ [[AvgDmg]] ] = [[5.0]],[ [[Dice]] ] = [[2D4]],[ [[Worn]] ] = [[one-handed]],},
{[ [[Flags]] ] = {252},[ [[Type]] ] = [[PEN]],[ [[Name]] ] = [[a vulture feather]],[ [[Weight]] ] = 0.04,[ [[Value]] ] = 0,[ [[Worn]] ] = [[HOLD]],[ [[Level]] ] = 15,[ [[Apply]] ] = {253},},
{[ [[Flags]] ] = {254},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a robe of the 3rd Eldorian Guard]],[ [[Weight]] ] = 3,[ [[Value]] ] = 0,[ [[Worn]] ] = [[BODY]],[ [[Level]] ] = 12,[ [[Apply]] ] = {255},},
{[ [[Flags]] ] = {256},[ [[Type]] ] = [[FOOD]],[ [[Name]] ] = [[a shoot of thyme]],[ [[Weight]] ] = 0.1,[ [[Value]] ] = 0,[ [[Level]] ] = 0,[ [[Fillingness]] ] = [[1]],},
{[ [[Type]] ] = [[TREASURE]],[ [[Flags]] ] = {257},[ [[Level]] ] = 40,[ [[Name]] ] = [[a monocle]],[ [[Weight]] ] = 0.07,[ [[Value]] ] = 250,[ [[Worn]] ] = [[EYES]],[ [[Provides]] ] = {258},[ [[Apply]] ] = {259},},
{[ [[Type]] ] = [[ARMOR]],[ [[Flags]] ] = {260},[ [[Worn]] ] = [[HEAD]],[ [[Name]] ] = [[Helm of the Protector]],[ [[Weight]] ] = 2.6,[ [[Value]] ] = 0,[ [[Level]] ] = 41,[ [[Provides]] ] = {261},[ [[Apply]] ] = {262},},
{[ [[Flags]] ] = {263},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a striking jade necklace]],[ [[Weight]] ] = 0.6,[ [[Value]] ] = 4500,[ [[Worn]] ] = [[NECK]],[ [[Level]] ] = 20,[ [[Apply]] ] = {264},},
{[ [[Flags]] ] = {265},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a citrine shard]],[ [[Weight]] ] = 0.01,[ [[Value]] ] = 1500,[ [[Level]] ] = 0,[ [[Apply]] ] = {266},},
{[ [[Flags]] ] = {267},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a thin sheet of cloud]],[ [[Weight]] ] = 0.01,[ [[Value]] ] = 1400,[ [[Worn]] ] = [[BODY]],[ [[Level]] ] = 70,[ [[Apply]] ] = {268},},
{[ [[Flags]] ] = {269},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a bluish-silver helm]],[ [[Weight]] ] = 6.75,[ [[Value]] ] = 700,[ [[Worn]] ] = [[HEAD]],[ [[Level]] ] = 35,[ [[Apply]] ] = {270},},
{[ [[Flags]] ] = {271},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[Studded Gauntlets of the Protector]],[ [[Weight]] ] = 1.1,[ [[Value]] ] = 0,[ [[Worn]] ] = [[HANDS]],[ [[Level]] ] = 41,[ [[Apply]] ] = {272},},
{[ [[Flags]] ] = {273},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[a thin copper bracelet]],[ [[Weight]] ] = 0.07,[ [[Value]] ] = 0,[ [[Worn]] ] = [[WRIST]],[ [[Level]] ] = 1,[ [[Apply]] ] = {274},},
{[ [[Type]] ] = [[LIGHT]],[ [[Is]] ] = {275},[ [[Flags]] ] = {276},[ [[Name]] ] = [[an ornamental christmas ball]],[ [[Weight]] ] = 0.06,[ [[Value]] ] = 0,[ [[Worn]] ] = [[EAR OBELT]],[ [[Hours]] ] = [[Infinate]],[ [[Level]] ] = 1,},
{[ [[Flags]] ] = {277},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a legendary ice fang]],[ [[Weight]] ] = 0.2,[ [[Value]] ] = 1900,[ [[Worn]] ] = [[EAR]],[ [[Level]] ] = 43,[ [[Apply]] ] = {278},},
{[ [[Dice]] ] = [[3D10]],[ [[Level]] ] = 30,[ [[Flags]] ] = {279},[ [[Worn]] ] = [[two-handed]],[ [[Name]] ] = [[a jagged greataxe]],[ [[Weight]] ] = 12,[ [[Value]] ] = 500,[ [[AvgDmg]] ] = [[16.5]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {280},},
{[ [[Flags]] ] = {281},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[trainee greaves]],[ [[Weight]] ] = 15,[ [[Value]] ] = 0,[ [[Worn]] ] = [[LEGS]],[ [[Level]] ] = 1,[ [[Apply]] ] = {282},},
{[ [[Type]] ] = [[CONTAINER]],[ [[Capacity]] ] = [[200]],[ [[Reduction]] ] = [[0%]],[ [[Flags]] ] = {283},[ [[Name]] ] = [[a leather saddle]],[ [[Weight]] ] = 8,[ [[Value]] ] = 100,[ [[Level]] ] = 10,[ [[Worn]] ] = [[BODY]],[ [[Apply]] ] = {284},},
{[ [[Type]] ] = [[CONTAINER]],[ [[Capacity]] ] = [[5000]],[ [[Reduction]] ] = [[0%]],[ [[Flags]] ] = {285},[ [[Name]] ] = [[a black leather bag]],[ [[Weight]] ] = 1,[ [[Value]] ] = 100,[ [[Level]] ] = 1,[ [[Worn]] ] = [[OBELT]],},
{[ [[Flags]] ] = {286},[ [[Type]] ] = [[TRASH]],[ [[Name]] ] = [[a wand of the 3rd Black Legion]],[ [[Weight]] ] = 1.4,[ [[Value]] ] = 0,[ [[Worn]] ] = [[HOLD]],[ [[Level]] ] = 8,},
{[ [[Type]] ] = [[TREASURE]],[ [[Specials]] ] = {287},[ [[Flags]] ] = {288},[ [[Worn]] ] = [[EYES]],[ [[Name]] ] = [[a bear claw tattoo]],[ [[Weight]] ] = 0.01,[ [[Value]] ] = 3000,[ [[Level]] ] = 20,[ [[Provides]] ] = {289},[ [[Apply]] ] = {290},},
{[ [[Flags]] ] = {291},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[the Shield of Darkness]],[ [[Weight]] ] = 2,[ [[Value]] ] = 600,[ [[Worn]] ] = [[SHIELD]],[ [[Level]] ] = 40,[ [[Apply]] ] = {292},},
{[ [[Flags]] ] = {293},[ [[Type]] ] = [[TRASH]],[ [[Name]] ] = [[a skull of the 3rd Black Legion]],[ [[Weight]] ] = 2.2,[ [[Value]] ] = 0,[ [[Level]] ] = 8,},
{[ [[Dice]] ] = [[3D9]],[ [[AvgDmg]] ] = [[15.0]],[ [[Flags]] ] = {294},[ [[Level]] ] = 20,[ [[Name]] ] = [[a dwarven war axe]],[ [[Weight]] ] = 4,[ [[Value]] ] = 9000,[ [[Worn]] ] = [[two-handed]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {295},},
{[ [[Dice]] ] = [[4D11]],[ [[Level]] ] = 35,[ [[Flags]] ] = {296},[ [[Worn]] ] = [[two-handed]],[ [[Name]] ] = [[an alabaster-pommelled broadsword]],[ [[Weight]] ] = 2.2,[ [[Value]] ] = 1000,[ [[AvgDmg]] ] = [[24.0]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {297},},
{[ [[Flags]] ] = {298},[ [[Type]] ] = [[POTION]],[ [[Name]] ] = [[a clear vial]],[ [[Weight]] ] = 0.1,[ [[Value]] ] = 100,[ [[Level]] ] = 17,[ [[Casts]] ] = {299},},
{[ [[Dice]] ] = [[3D3]],[ [[AvgDmg]] ] = [[6.0]],[ [[Flags]] ] = {300},[ [[Level]] ] = 15,[ [[Name]] ] = [[the Nightblade]],[ [[Weight]] ] = 4,[ [[Value]] ] = 500,[ [[Worn]] ] = [[one-handed]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {301},},
{[ [[Type]] ] = [[LIGHT]],[ [[Flags]] ] = {302},[ [[Level]] ] = 15,[ [[Name]] ] = [[a pale circlet]],[ [[Weight]] ] = 1.4,[ [[Value]] ] = 5000,[ [[Worn]] ] = [[HEAD]],[ [[Hours]] ] = [[400]],[ [[Apply]] ] = {303},},
{[ [[Flags]] ] = {304},[ [[Type]] ] = [[ARMOR]],[ [[Name]] ] = [[Bracer of the Protector]],[ [[Weight]] ] = 0.91,[ [[Value]] ] = 0,[ [[Worn]] ] = [[WRIST]],[ [[Level]] ] = 41,[ [[Apply]] ] = {305},},
{[ [[Flags]] ] = {306},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a crushed aquamarine]],[ [[Weight]] ] = 0.01,[ [[Value]] ] = 1000,[ [[Level]] ] = 0,[ [[Apply]] ] = {307},},
{[ [[Type]] ] = [[TREASURE]],[ [[Specials]] ] = {308},[ [[Flags]] ] = {309},[ [[Worn]] ] = [[EYES]],[ [[Name]] ] = [[wolf eye tattoos]],[ [[Weight]] ] = 0.01,[ [[Value]] ] = 5000,[ [[Level]] ] = 40,[ [[Provides]] ] = {310},[ [[Apply]] ] = {311},},
{[ [[Dice]] ] = [[2D3]],[ [[Level]] ] = 1,[ [[Flags]] ] = {312},[ [[Worn]] ] = [[one-handed]],[ [[Name]] ] = [[a broken dragon's fist mace]],[ [[Weight]] ] = 1.4,[ [[Value]] ] = 1,[ [[AvgDmg]] ] = [[4.0]],[ [[Type]] ] = [[WEAPON]],[ [[Apply]] ] = {313},},
{[ [[Flags]] ] = {314},[ [[Type]] ] = [[TRASH]],[ [[Name]] ] = [[a ring of the 3rd Black Legion]],[ [[Weight]] ] = 0.02,[ [[Value]] ] = 0,[ [[Worn]] ] = [[FINGER]],[ [[Level]] ] = 8,},
{[ [[Type]] ] = [[STAFF]],[ [[Specials]] ] = {315},[ [[Flags]] ] = {316},[ [[Casts]] ] = {317},[ [[Name]] ] = [[a black and gold harp]],[ [[Weight]] ] = 3,[ [[Value]] ] = 0,[ [[Level]] ] = 70,[ [[Worn]] ] = [[HOLD OBELT]],[ [[Apply]] ] = {318},},
{[ [[Flags]] ] = {319},[ [[Type]] ] = [[POTION]],[ [[Name]] ] = [[a bottle of nostrum]],[ [[Weight]] ] = 0.3,[ [[Value]] ] = 8000,[ [[Level]] ] = 45,[ [[Casts]] ] = {320},},
{[ [[Flags]] ] = {321},[ [[Type]] ] = [[TREASURE]],[ [[Name]] ] = [[a bat tooth necklace]],[ [[Weight]] ] = 0.4,[ [[Value]] ] = 145,[ [[Worn]] ] = [[NECK]],[ [[Level]] ] = 5,[ [[Apply]] ] = {322},},
{[ [[Flags]] ] = {323},[ [[Type]] ] = [[KEY]],[ [[Name]] ] = [[the aspen key]],[ [[Weight]] ] = 0.05,[ [[Value]] ] = 0,[ [[Worn]] ] = [[HOLD]],[ [[Level]] ] = 1,},
{[ [[Type]] ] = [[TREASURE]],[ [[Specials]] ] = {324},[ [[Flags]] ] = {325},[ [[Name]] ] = [[the jewel of the heart]],[ [[Weight]] ] = 0.2,[ [[Value]] ] = 1782,[ [[Level]] ] = 5,[ [[Worn]] ] = [[NECK]],[ [[Apply]] ] = {326},},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[ARMOR]] ] = [[0]],},
{[1] = [[!SORCERER]],[2] = [[!DRUID]],[3] = [[!NECROMANCER]],[4] = [[!CONJURER]],[5] = [[!MONK]],[6] = [[!THIEF]],[7] = [[!PYROMANCER]],[8] = [[!CRYOMANCER]],[9] = [[!ILLUSIONIST]],[10] = [[!PRIEST]],[11] = [[!DIABOLIST]],},
{[ [[ARMOR]] ] = [[5]],},
{[1] = [[!RENT]],},
{[1] = [[MAGIC]],[2] = [[!SORCERER]],[3] = [[!NECROMANCER]],[4] = [[!CONJURER]],[5] = [[!PYROMANCER]],[6] = [[!CRYOMANCER]],[7] = [[!ILLUSIONIST]],},
{[ [[DAMROLL]] ] = [[+3]],[ [[HITROLL]] ] = [[+3]],},
{[1] = [[INVISIBLE]],},
{[1] = [[!BERSERKER]],[2] = [[MAGIC]],[3] = [[!DROP]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!ROGUE]],[7] = [[!WARRIOR]],[8] = [[!SELL]],[9] = [[!PALADIN]],[10] = [[!ANTI_PALADIN]],[11] = [[!DRUID]],[12] = [[!SHAMAN]],[13] = [[!ASSASSIN]],[14] = [[!MERCENARY]],[15] = [[!NECROMANCER]],[16] = [[!CONJURER]],[20] = [[!PYROMANCER]],[17] = [[!MONK]],[21] = [[!CRYOMANCER]],[18] = [[!BARD]],[22] = [[!ILLUSIONIST]],[19] = [[!THIEF]],[23] = [[!PRIEST]],[24] = [[!DIABOLIST]],},
{[1] = [[!TRACK]],},
{[ [[MAXMOVE]] ] = [[+30]],[ [[HITROLL]] ] = [[+1]],[ [[DAMROLL]] ] = [[+2]],[ [[ARMOR]] ] = [[7]],},
{[1] = [[!SORCERER]],[2] = [[!CLERIC]],[3] = [[!DRUID]],[4] = [[!SHAMAN]],[5] = [[!NECROMANCER]],[6] = [[!CONJURER]],[7] = [[!MONK]],[8] = [[!PYROMANCER]],[9] = [[!CRYOMANCER]],[10] = [[!ILLUSIONIST]],[11] = [[!PRIEST]],[12] = [[!DIABOLIST]],},
{[ [[DAMROLL]] ] = [[+1]],},
{[1] = [[!EVIL]],[2] = [[!SORCERER]],[3] = [[!NECROMANCER]],[4] = [[!CONJURER]],[5] = [[!PYROMANCER]],[6] = [[!CRYOMANCER]],[7] = [[!ILLUSIONIST]],},
{[ [[HITPOINTS]] ] = [[+5]],[ [[ARMOR]] ] = [[13]],[ [[CON]] ] = [[+2]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[!EVIL]],[2] = [[!SORCERER]],[3] = [[!NECROMANCER]],[4] = [[!CONJURER]],[5] = [[!PYROMANCER]],[6] = [[!CRYOMANCER]],[7] = [[!ILLUSIONIST]],},
{[ [[ARMOR]] ] = [[6]],[ [[DEX]] ] = [[+2]],},
{[1] = [[MAGIC]],},
{[1] = [[remove poison]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[ARMOR]] ] = [[10]],[ [[HITROLL]] ] = [[+1]],[ [[DAMROLL]] ] = [[+1]],[ [[HITPOINTS]] ] = [[+15]],},
{[1] = [[baton_cone_of_cold]],},
{[1] = [[MAGIC]],[2] = [[!SORCERER]],[3] = [[!CLERIC]],[4] = [[!ROGUE]],[5] = [[!DRUID]],[6] = [[!SHAMAN]],[7] = [[!ASSASSIN]],[8] = [[!NECROMANCER]],[9] = [[!CONJURER]],[10] = [[!BURN]],[11] = [[!LOCATE]],[12] = [[FLOAT]],},
{[1] = [[GLOW]],[2] = [[!BERSERKER]],[3] = [[MAGIC]],[4] = [[!DROP]],[5] = [[!SORCERER]],[6] = [[!CLERIC]],[7] = [[!ROGUE]],[8] = [[!WARRIOR]],[9] = [[!SELL]],[10] = [[!PALADIN]],[11] = [[!ANTI_PALADIN]],[12] = [[!DRUID]],[13] = [[!SHAMAN]],[14] = [[!ASSASSIN]],[15] = [[!MERCENARY]],[16] = [[!NECROMANCER]],[17] = [[!CONJURER]],[18] = [[FLOAT]],[19] = [[!MONK]],[20] = [[!BARD]],[21] = [[!THIEF]],[22] = [[!PYROMANCER]],[23] = [[!CRYOMANCER]],[24] = [[!ILLUSIONIST]],[25] = [[!PRIEST]],[26] = [[!DIABOLIST]],},
{[ [[ARMOR]] ] = [[13]],[ [[HITPOINTS]] ] = [[+18]],[ [[CON]] ] = [[+3]],},
{[1] = [[MAGIC]],},
{[ [[STR]] ] = [[+2]],[ [[ARMOR]] ] = [[2]],[ [[CON]] ] = [[+2]],},
{[1] = [[GLOW]],[2] = [[HUM]],},
{[1] = [[GLOW]],[2] = [[HUM]],},
{[ [[SAVING_BREATH]] ] = [[-2]],},
{[1] = [[HUM]],[2] = [[!GOOD]],[3] = [[!NEUTRAL]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!NECROMANCER]],[7] = [[!CONJURER]],[8] = [[!MONK]],[9] = [[!PYROMANCER]],[10] = [[!CRYOMANCER]],[11] = [[!ILLUSIONIST]],[12] = [[!PRIEST]],[13] = [[!DIABOLIST]],},
{[ [[DAMROLL]] ] = [[+2]],},
{[1] = [[HUM]],[2] = [[!EVIL]],[3] = [[FLOAT]],},
{[ [[INT]] ] = [[+2]],[ [[WIS]] ] = [[+2]],[ [[ARMOR]] ] = [[0]],[ [[CHA]] ] = [[+2]],},
{[1] = [[GLOW]],[2] = [[MAGIC]],[3] = [[FLOAT]],},
{[ [[MAXMOVE]] ] = [[+10]],[ [[WIS]] ] = [[+3]],[ [[HITPOINTS]] ] = [[+5]],[ [[ARMOR]] ] = [[4]],},
{[1] = [[!BERSERKER]],[2] = [[MAGIC]],[3] = [[!DROP]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!ROGUE]],[7] = [[!WARRIOR]],[8] = [[!SELL]],[9] = [[!PALADIN]],[10] = [[!ANTI_PALADIN]],[11] = [[!DRUID]],[12] = [[!SHAMAN]],[13] = [[!ASSASSIN]],[14] = [[!MERCENARY]],[15] = [[!NECROMANCER]],[16] = [[!CONJURER]],[20] = [[!PYROMANCER]],[17] = [[!MONK]],[21] = [[!CRYOMANCER]],[18] = [[!BARD]],[22] = [[!ILLUSIONIST]],[19] = [[!THIEF]],[23] = [[!PRIEST]],[24] = [[!DIABOLIST]],},
{[ [[STR]] ] = [[+3]],[ [[DEX]] ] = [[+2]],[ [[DAMROLL]] ] = [[+2]],[ [[ARMOR]] ] = [[35]],},
{[1] = [[GLOW]],},
{[1] = [[cure light]],[2] = [[cure light]],[3] = [[and cure light]],},
{[1] = [[FLOAT]],},
{[ [[CHA]] ] = [[+2]],[ [[ARMOR]] ] = [[3]],[ [[HITPOINTS]] ] = [[+3]],},
{[1] = [[GLOW]],[2] = [[!BERSERKER]],[3] = [[MAGIC]],[4] = [[!ROGUE]],[5] = [[!WARRIOR]],[6] = [[!ASSASSIN]],[7] = [[!MERCENARY]],[8] = [[FLOAT]],[9] = [[!THIEF]],},
{[ [[INT]] ] = [[+3]],[ [[STR]] ] = [[+3]],[ [[ARMOR]] ] = [[0]],},
{[1] = [[HUM]],[2] = [[!BERSERKER]],[3] = [[!EVIL]],[4] = [[!SORCERER]],[5] = [[!WARRIOR]],[6] = [[!ANTI_PALADIN]],[7] = [[!RANGER]],[8] = [[!ASSASSIN]],[9] = [[!MERCENARY]],[10] = [[!NECROMANCER]],[11] = [[!BARD]],[12] = [[!PYROMANCER]],[13] = [[!CRYOMANCER]],[14] = [[!ILLUSIONIST]],},
{[ [[INT]] ] = [[+1]],[ [[WIS]] ] = [[+1]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[tempest of saint augustine]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[cure critic]],[2] = [[cure critic]],[3] = [[and cure critic]],},
{[1] = [[!BERSERKER]],[2] = [[!GOOD]],[3] = [[!NEUTRAL]],[4] = [[!SORCERER]],[5] = [[!ROGUE]],[6] = [[!WARRIOR]],[7] = [[!PALADIN]],[8] = [[!RANGER]],[9] = [[!ASSASSIN]],[10] = [[!MERCENARY]],[11] = [[!NECROMANCER]],[12] = [[!CONJURER]],[13] = [[!BARD]],[14] = [[!THIEF]],[15] = [[!PYROMANCER]],[16] = [[!CRYOMANCER]],[17] = [[!ILLUSIONIST]],},
{[ [[HITPOINTS]] ] = [[+15]],[ [[DAMROLL]] ] = [[-1]],[ [[ARMOR]] ] = [[0]],},
{[1] = [[!SELL]],},
{[1] = [[GLOW]],[2] = [[MAGIC]],[3] = [[!GOOD]],[4] = [[!SELL]],[5] = [[!DRUID]],[6] = [[FLOAT]],},
{[ [[AGE]] ] = [[+5]],[ [[WIS]] ] = [[-2]],[ [[DEX]] ] = [[+2]],[ [[ARMOR]] ] = [[+2]],},
{[1] = [[FLOAT]],},
{[1] = [[MAGIC]],},
{[ [[HITROLL]] ] = [[+2]],[ [[ARMOR]] ] = [[1]],[ [[DAMROLL]] ] = [[+1]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[DAMROLL]] ] = [[+2]],[ [[ARMOR]] ] = [[1]],[ [[STR]] ] = [[+1]],[ [[CON]] ] = [[+1]],},
{[1] = [[!DROP]],[2] = [[!SELL]],},
{[ [[DAMROLL]] ] = [[+4]],[ [[HITROLL]] ] = [[+2]],[ [[STR]] ] = [[+3]],[ [[ARMOR]] ] = [[10]],},
{[1] = [[!INVIS]],[2] = [[!DROP]],[3] = [[PERMANENT]],[4] = [[!SELL]],[5] = [[!BURN]],[6] = [[!LOCATE]],},
{[1] = [[PROT_FIRE]],},
{[ [[SAVING_PARA]] ] = [[-10]],[ [[ARMOR]] ] = [[11]],[ [[SAVING_BREATH]] ] = [[-20]],[ [[DAMROLL]] ] = [[+1]],[ [[HITROLL]] ] = [[+1]],[ [[HITPOINTS]] ] = [[+50]],[ [[SAVING_SPELL]] ] = [[-10]],},
{[1] = [[MAGIC]],},
{[ [[ARMOR]] ] = [[2]],[ [[STR]] ] = [[-1]],[ [[SAVING_SPELL]] ] = [[-20]],},
{[1] = [[MAGIC]],[2] = [[!SORCERER]],[3] = [[!DRUID]],[4] = [[!NECROMANCER]],[5] = [[!CONJURER]],[6] = [[!MONK]],[7] = [[!PYROMANCER]],[8] = [[!CRYOMANCER]],[9] = [[!ILLUSIONIST]],},
{[ [[WIS]] ] = [[+2]],},
{[1] = [[GLOW]],},
{[1] = [[FARSEE]],},
{[ [[ARMOR]] ] = [[0]],[ [[DEX]] ] = [[+5]],},
{[1] = [[!SORCERER]],[2] = [[!CLERIC]],[3] = [[!ROGUE]],[4] = [[!PALADIN]],[5] = [[!ANTI_PALADIN]],[6] = [[!DRUID]],[7] = [[!SHAMAN]],[8] = [[!ASSASSIN]],[9] = [[!NECROMANCER]],[10] = [[!CONJURER]],[11] = [[FLOAT]],[12] = [[!MONK]],[13] = [[!BARD]],[14] = [[!THIEF]],[15] = [[!PYROMANCER]],[16] = [[!CRYOMANCER]],[17] = [[!ILLUSIONIST]],[18] = [[!PRIEST]],[19] = [[!DIABOLIST]],},
{[1] = [[DET_ALIGN]],[2] = [[DET_INVIS]],[3] = [[DET_MAGIC]],[4] = [[SENSE_LIFE]],[5] = [[FARSEE]],},
{[ [[DAMROLL]] ] = [[+3]],[ [[HITROLL]] ] = [[+3]],[ [[ARMOR]] ] = [[3]],[ [[PERCEPTION]] ] = [[+200]],},
{[1] = [[!SORCERER]],[2] = [[!ROGUE]],[3] = [[!DRUID]],[4] = [[!SHAMAN]],[5] = [[!ASSASSIN]],[6] = [[!NECROMANCER]],[7] = [[!CONJURER]],[8] = [[!MONK]],},
{[ [[DAMROLL]] ] = [[+3]],[ [[DEX]] ] = [[-5]],},
{[1] = [[MAGIC]],[2] = [[FLOAT]],},
{[1] = [[identify]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[innate chaz]],[2] = [[enhance strength]],},
{[1] = [[!BERSERKER]],[2] = [[!EVIL]],[3] = [[!ROGUE]],[4] = [[!WARRIOR]],[5] = [[!ANTI_PALADIN]],[6] = [[!RANGER]],[7] = [[!ASSASSIN]],[8] = [[!MERCENARY]],[9] = [[!NECROMANCER]],[10] = [[!THIEF]],},
{[ [[ARMOR]] ] = [[7]],[ [[INT]] ] = [[+2]],},
{[1] = [[!SORCERER]],[2] = [[!NECROMANCER]],[3] = [[!CONJURER]],[4] = [[!PYROMANCER]],[5] = [[!CRYOMANCER]],[6] = [[!ILLUSIONIST]],},
{[ [[INT]] ] = [[-2]],[ [[ARMOR]] ] = [[7]],[ [[CON]] ] = [[+2]],},
{[1] = [[quest_pyro_get]],},
{[1] = [[MAGIC]],[2] = [[!GOOD]],[3] = [[!NEUTRAL]],[4] = [[FLOAT]],[5] = [[!FALL]],[6] = [[!CRYOMANCER]],},
{[ [[DAMROLL]] ] = [[+2]],[ [[WIS]] ] = [[-1]],},
{[1] = [[GLOW]],[2] = [[!EVIL]],[3] = [[!SORCERER]],[4] = [[!CLERIC]],[5] = [[!DRUID]],[6] = [[!SHAMAN]],[7] = [[!NECROMANCER]],[8] = [[!CONJURER]],[9] = [[!MONK]],[10] = [[ELVEN]],[11] = [[!PYROMANCER]],[12] = [[!CRYOMANCER]],[13] = [[!ILLUSIONIST]],[14] = [[!PRIEST]],[15] = [[!DIABOLIST]],},
{[ [[DAMROLL]] ] = [[+1]],},
{[1] = [[!GOOD]],[2] = [[!NEUTRAL]],[3] = [[FLOAT]],},
{[ [[HITROLL]] ] = [[-1]],[ [[ARMOR]] ] = [[4]],[ [[DEX]] ] = [[+1]],},
{[1] = [[!EVIL]],[2] = [[!SORCERER]],[3] = [[!NECROMANCER]],[4] = [[!CONJURER]],[5] = [[!PYROMANCER]],[6] = [[!CRYOMANCER]],[7] = [[!ILLUSIONIST]],},
{[ [[ARMOR]] ] = [[7]],[ [[INT]] ] = [[+2]],},
{[1] = [[GLOW]],[2] = [[!GOOD]],[3] = [[!NEUTRAL]],},
{[ [[INT]] ] = [[+9]],[ [[PERCEPTION]] ] = [[+100]],[ [[ARMOR]] ] = [[2]],[ [[SAVING_SPELL]] ] = [[-3]],},
{[1] = [[GLOW]],[2] = [[MAGIC]],},
{[1] = [[harm]],},
{[1] = [[Treasure]],[2] = [[Hunter]],[3] = [[treasure]],[4] = [[get]],[5] = [[Treasure]],[6] = [[Hunter]],[7] = [[object]],[8] = [[give]],},
{[1] = [[MAGIC]],},
{[ [[STR]] ] = [[+1]],[ [[DEX]] ] = [[-2]],[ [[ARMOR]] ] = [[10]],},
{[1] = [[FLOAT]],},
{[ [[ARMOR]] ] = [[1]],[ [[HITPOINTS]] ] = [[+3]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[ARMOR]] ] = [[0]],[ [[INT]] ] = [[+2]],},
{[1] = [[GLOW]],[2] = [[HUM]],[3] = [[!BERSERKER]],[4] = [[MAGIC]],[5] = [[!DROP]],[6] = [[!SORCERER]],[7] = [[!CLERIC]],[8] = [[!ROGUE]],[9] = [[!WARRIOR]],[10] = [[!SELL]],[11] = [[!PALADIN]],[12] = [[!ANTI_PALADIN]],[13] = [[!DRUID]],[14] = [[!SHAMAN]],[15] = [[!ASSASSIN]],[16] = [[!MERCENARY]],[17] = [[!NECROMANCER]],[18] = [[!CONJURER]],[19] = [[!MONK]],[20] = [[!BARD]],[21] = [[!THIEF]],[22] = [[!PYROMANCER]],[23] = [[!CRYOMANCER]],[24] = [[!ILLUSIONIST]],[25] = [[!PRIEST]],[26] = [[!DIABOLIST]],},
{[ [[INT]] ] = [[+3]],[ [[ARMOR]] ] = [[7]],[ [[DAMROLL]] ] = [[+1]],[ [[HITROLL]] ] = [[+2]],[ [[DEX]] ] = [[+2]],[ [[HITPOINTS]] ] = [[+25]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[HITROLL]] ] = [[+1]],[ [[HITPOINTS]] ] = [[+2]],[ [[ARMOR]] ] = [[0]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[ARMOR]] ] = [[0]],[ [[SAVING_BREATH]] ] = [[-10]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[GLOW]],[2] = [[MAGIC]],[3] = [[!EVIL]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!DRUID]],[7] = [[!NECROMANCER]],[8] = [[!CONJURER]],[9] = [[!MONK]],[10] = [[ELVEN]],[11] = [[!PYROMANCER]],[12] = [[!CRYOMANCER]],[13] = [[!ILLUSIONIST]],[14] = [[!PRIEST]],[15] = [[!DIABOLIST]],},
{[ [[STR]] ] = [[+1]],[ [[DAMROLL]] ] = [[+1]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[CHA]] ] = [[+2]],[ [[ARMOR]] ] = [[0]],[ [[HITROLL]] ] = [[+1]],},
{[1] = [[forage]],[2] = [[obj]],[3] = [[normalizer]],[4] = [[Ranger]],[5] = [[Trophy]],[6] = [[command]],[7] = [[forage]],[8] = [[Ranger]],[9] = [[trophy]],[10] = [[attack]],[11] = [[counter]],},
{[1] = [[!SORCERER]],[2] = [[!CLERIC]],[3] = [[!ROGUE]],[4] = [[!PALADIN]],[5] = [[!ANTI_PALADIN]],[6] = [[!DRUID]],[7] = [[!SHAMAN]],[8] = [[!ASSASSIN]],[9] = [[!NECROMANCER]],[10] = [[!CONJURER]],[11] = [[FLOAT]],[12] = [[!MONK]],[13] = [[!BARD]],[14] = [[!THIEF]],[15] = [[!PYROMANCER]],[16] = [[!CRYOMANCER]],[17] = [[!ILLUSIONIST]],[18] = [[!PRIEST]],[19] = [[!DIABOLIST]],},
{[1] = [[SENSE_LIFE]],},
{[ [[DAMROLL]] ] = [[+1]],[ [[HITROLL]] ] = [[+1]],[ [[ARMOR]] ] = [[2]],[ [[PERCEPTION]] ] = [[+80]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[ARMOR]] ] = [[1]],[ [[HITPOINTS]] ] = [[+12]],},
{[1] = [[!BERSERKER]],[2] = [[MAGIC]],[3] = [[!DROP]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!ROGUE]],[7] = [[!WARRIOR]],[8] = [[!SELL]],[9] = [[!PALADIN]],[10] = [[!ANTI_PALADIN]],[11] = [[!DRUID]],[12] = [[!SHAMAN]],[13] = [[!ASSASSIN]],[14] = [[!MERCENARY]],[15] = [[!NECROMANCER]],[16] = [[!CONJURER]],[20] = [[!PYROMANCER]],[17] = [[!MONK]],[21] = [[!CRYOMANCER]],[18] = [[!BARD]],[22] = [[!ILLUSIONIST]],[19] = [[!THIEF]],[23] = [[!PRIEST]],[24] = [[!DIABOLIST]],},
{[ [[INT]] ] = [[+2]],[ [[ARMOR]] ] = [[7]],[ [[HITROLL]] ] = [[+1]],[ [[DAMROLL]] ] = [[+1]],[ [[HITPOINTS]] ] = [[+25]],},
{[1] = [[!SELL]],[2] = [[FLOAT]],},
{[1] = [[FLOAT]],},
{[ [[DAMROLL]] ] = [[+1]],[ [[STR]] ] = [[+2]],[ [[ARMOR]] ] = [[3]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[GLOW]],[2] = [[!BERSERKER]],[3] = [[MAGIC]],[4] = [[!DROP]],[5] = [[!SORCERER]],[6] = [[!CLERIC]],[7] = [[!ROGUE]],[8] = [[!WARRIOR]],[9] = [[!SELL]],[10] = [[!PALADIN]],[11] = [[!ANTI_PALADIN]],[12] = [[!DRUID]],[13] = [[!SHAMAN]],[14] = [[!ASSASSIN]],[15] = [[!MERCENARY]],[16] = [[!NECROMANCER]],[17] = [[!CONJURER]],[18] = [[FLOAT]],[19] = [[!MONK]],[20] = [[!BARD]],[21] = [[!THIEF]],[22] = [[!PYROMANCER]],[23] = [[!CRYOMANCER]],[24] = [[!ILLUSIONIST]],[25] = [[!PRIEST]],[26] = [[!DIABOLIST]],},
{[ [[WIS]] ] = [[+3]],[ [[STR]] ] = [[+2]],[ [[ARMOR]] ] = [[3]],},
{[1] = [[FLOAT]],},
{[ [[ARMOR]] ] = [[3]],[ [[DEX]] ] = [[+1]],[ [[CON]] ] = [[+3]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[dark presence]],},
{[1] = [[!GOOD]],[2] = [[!SORCERER]],[3] = [[!PALADIN]],[4] = [[!RANGER]],[5] = [[!DRUID]],[6] = [[!NECROMANCER]],[7] = [[!CONJURER]],[8] = [[!MONK]],[9] = [[!PYROMANCER]],[10] = [[!CRYOMANCER]],[11] = [[!ILLUSIONIST]],[12] = [[!PRIEST]],},
{[ [[HITROLL]] ] = [[-2]],[ [[DAMROLL]] ] = [[+2]],[ [[CON]] ] = [[+3]],},
{[1] = [[MAGIC]],[2] = [[!SELL]],[3] = [[FLOAT]],},
{[1] = [[recall]],},
{[1] = [[!EVIL]],[2] = [[!SORCERER]],[3] = [[!CLERIC]],[4] = [[!DRUID]],[5] = [[!SHAMAN]],[6] = [[!NECROMANCER]],[7] = [[!CONJURER]],[8] = [[!MONK]],[9] = [[ELVEN]],[10] = [[!PYROMANCER]],[11] = [[!CRYOMANCER]],[12] = [[!ILLUSIONIST]],[13] = [[!PRIEST]],[14] = [[!DIABOLIST]],},
{[1] = [[FLOAT]],},
{[ [[INT]] ] = [[+1]],[ [[WIS]] ] = [[+1]],[ [[MAXMOVE]] ] = [[+15]],},
{[1] = [[!EVIL]],},
{[ [[INT]] ] = [[+2]],[ [[WIS]] ] = [[+2]],[ [[ARMOR]] ] = [[5]],[ [[HITPOINTS]] ] = [[+5]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[DET_INVIS]],[2] = [[FARSEE]],},
{[ [[WIS]] ] = [[+2]],[ [[ARMOR]] ] = [[0]],[ [[PERCEPTION]] ] = [[+150]],},
{[1] = [[!BERSERKER]],[2] = [[MAGIC]],[3] = [[!DROP]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!ROGUE]],[7] = [[!WARRIOR]],[8] = [[!SELL]],[9] = [[!PALADIN]],[10] = [[!ANTI_PALADIN]],[11] = [[!DRUID]],[12] = [[!SHAMAN]],[13] = [[!ASSASSIN]],[14] = [[!MERCENARY]],[15] = [[!NECROMANCER]],[16] = [[!CONJURER]],[20] = [[!PYROMANCER]],[17] = [[!MONK]],[21] = [[!CRYOMANCER]],[18] = [[!BARD]],[22] = [[!ILLUSIONIST]],[19] = [[!THIEF]],[23] = [[!PRIEST]],},
{[1] = [[DET_INVIS]],},
{[ [[HITROLL]] ] = [[+1]],[ [[ARMOR]] ] = [[5]],[ [[DAMROLL]] ] = [[+2]],},
{[1] = [[MAGIC]],},
{[ [[ARMOR]] ] = [[2]],[ [[HITROLL]] ] = [[+2]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[ARMOR]] ] = [[0]],},
{[1] = [[FLOAT]],[2] = [[!FALL]],},
{[ [[ARMOR]] ] = [[24]],[ [[HIT_REGEN]] ] = [[+5]],[ [[CHA]] ] = [[+4]],[ [[STR]] ] = [[-2]],[ [[CON]] ] = [[-2]],},
{[1] = [[MAGIC]],[2] = [[!EVIL]],[3] = [[!SORCERER]],[4] = [[!ROGUE]],[5] = [[!DRUID]],[6] = [[!ASSASSIN]],[7] = [[!NECROMANCER]],[8] = [[!CONJURER]],[9] = [[!MONK]],[10] = [[!BARD]],[11] = [[!THIEF]],[12] = [[!PYROMANCER]],[13] = [[!CRYOMANCER]],[14] = [[!ILLUSIONIST]],[15] = [[!DIABOLIST]],},
{[ [[HITROLL]] ] = [[+1]],[ [[ARMOR]] ] = [[7]],[ [[DEX]] ] = [[+2]],},
{[1] = [[!BERSERKER]],[2] = [[MAGIC]],[3] = [[!DROP]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!ROGUE]],[7] = [[!WARRIOR]],[8] = [[!SELL]],[9] = [[!PALADIN]],[10] = [[!ANTI_PALADIN]],[11] = [[!DRUID]],[12] = [[!SHAMAN]],[13] = [[!ASSASSIN]],[14] = [[!MERCENARY]],[15] = [[!NECROMANCER]],[16] = [[!CONJURER]],[20] = [[!PYROMANCER]],[17] = [[!MONK]],[21] = [[!CRYOMANCER]],[18] = [[!BARD]],[22] = [[!ILLUSIONIST]],[19] = [[!THIEF]],[23] = [[!PRIEST]],[24] = [[!DIABOLIST]],},
{[ [[HITROLL]] ] = [[+2]],[ [[ARMOR]] ] = [[4]],[ [[DAMROLL]] ] = [[+1]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[ARMOR]] ] = [[1]],[ [[SAVING_SPELL]] ] = [[-1]],},
{[1] = [[GLOW]],[2] = [[MAGIC]],},
{[1] = [[GLOW]],[2] = [[MAGIC]],},
{[1] = [[HUM]],},
{[ [[HITPOINTS]] ] = [[+75]],[ [[HITROLL]] ] = [[+3]],[ [[ARMOR]] ] = [[3]],[ [[DAMROLL]] ] = [[+3]],},
{[1] = [[!SORCERER]],[2] = [[!CLERIC]],[3] = [[!ROGUE]],[4] = [[!DRUID]],[5] = [[!SHAMAN]],[6] = [[!ASSASSIN]],[7] = [[!NECROMANCER]],[8] = [[!CONJURER]],[9] = [[!MONK]],[10] = [[!BARD]],[11] = [[!THIEF]],[12] = [[!PYROMANCER]],[13] = [[!CRYOMANCER]],[14] = [[!ILLUSIONIST]],[15] = [[!PRIEST]],[16] = [[!DIABOLIST]],},
{[ [[CON]] ] = [[+2]],},
{[1] = [[MAGIC]],[2] = [[!SORCERER]],[3] = [[!CLERIC]],[4] = [[!ROGUE]],[5] = [[!DRUID]],[6] = [[!SHAMAN]],[7] = [[!ASSASSIN]],[8] = [[!MERCENARY]],[9] = [[!NECROMANCER]],[10] = [[!CONJURER]],[11] = [[!BARD]],[12] = [[!THIEF]],[13] = [[!PYROMANCER]],[14] = [[!CRYOMANCER]],[15] = [[!ILLUSIONIST]],[16] = [[!PRIEST]],[17] = [[!DIABOLIST]],},
{[ [[HITROLL]] ] = [[+1]],[ [[ARMOR]] ] = [[6]],[ [[HITPOINTS]] ] = [[+7]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[CON]] ] = [[+2]],},
{[1] = [[MAGIC]],[2] = [[!BURN]],[3] = [[FLOAT]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[forage]],[2] = [[obj]],[3] = [[normalizer]],[4] = [[Ranger]],[5] = [[Trophy]],[6] = [[command]],[7] = [[forage]],[8] = [[Ranger]],[9] = [[trophy]],[10] = [[attack]],[11] = [[counter]],},
{[1] = [[!SORCERER]],[2] = [[!CLERIC]],[3] = [[!ROGUE]],[4] = [[!PALADIN]],[5] = [[!ANTI_PALADIN]],[6] = [[!DRUID]],[7] = [[!SHAMAN]],[8] = [[!ASSASSIN]],[9] = [[!NECROMANCER]],[10] = [[!CONJURER]],[11] = [[FLOAT]],[12] = [[!MONK]],[13] = [[!BARD]],[14] = [[!THIEF]],[15] = [[!PYROMANCER]],[16] = [[!CRYOMANCER]],[17] = [[!ILLUSIONIST]],[18] = [[!PRIEST]],[19] = [[!DIABOLIST]],},
{[1] = [[SENSE_LIFE]],},
{[ [[DAMROLL]] ] = [[+1]],[ [[HITROLL]] ] = [[+1]],[ [[ARMOR]] ] = [[1]],[ [[PERCEPTION]] ] = [[+60]],},
{[1] = [[MAGIC]],[2] = [[!GOOD]],},
{[ [[ARMOR]] ] = [[11]],[ [[HITROLL]] ] = [[+3]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[!SORCERER]],[2] = [[!CLERIC]],[3] = [[!ROGUE]],[4] = [[!DRUID]],[5] = [[!ASSASSIN]],[6] = [[!NECROMANCER]],[7] = [[!CONJURER]],[8] = [[!MONK]],[9] = [[!BARD]],[10] = [[DWARVEN]],[11] = [[!THIEF]],[12] = [[!PYROMANCER]],[13] = [[!CRYOMANCER]],[14] = [[!ILLUSIONIST]],[15] = [[!PRIEST]],[16] = [[!DIABOLIST]],},
{[ [[DEX]] ] = [[-3]],[ [[HITROLL]] ] = [[+1]],[ [[STR]] ] = [[-2]],[ [[DAMROLL]] ] = [[+1]],},
{[1] = [[!SORCERER]],[2] = [[!CLERIC]],[3] = [[!ROGUE]],[4] = [[!DRUID]],[5] = [[!SHAMAN]],[6] = [[!ASSASSIN]],[7] = [[!NECROMANCER]],[8] = [[!CONJURER]],[9] = [[!MONK]],[10] = [[!BARD]],[11] = [[!THIEF]],[12] = [[!PYROMANCER]],[13] = [[!CRYOMANCER]],[14] = [[!ILLUSIONIST]],[15] = [[!PRIEST]],[16] = [[!DIABOLIST]],},
{[ [[CHA]] ] = [[+3]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[invisibility]],[2] = [[protection from air]],},
{[1] = [[MAGIC]],[2] = [[!GOOD]],[3] = [[!NEUTRAL]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!DRUID]],[7] = [[!SHAMAN]],[8] = [[!NECROMANCER]],[9] = [[!CONJURER]],[10] = [[FLOAT]],[11] = [[!MONK]],[12] = [[ELVEN]],[13] = [[!PYROMANCER]],[14] = [[!CRYOMANCER]],[15] = [[!ILLUSIONIST]],[16] = [[!PRIEST]],[17] = [[!DIABOLIST]],},
{[ [[HITROLL]] ] = [[+1]],[ [[DAMROLL]] ] = [[+1]],[ [[WIS]] ] = [[-3]],},
{[1] = [[FLOAT]],[2] = [[!FALL]],},
{[ [[INT]] ] = [[+2]],[ [[WIS]] ] = [[+2]],[ [[ARMOR]] ] = [[+4]],[ [[CHAR_HEIGHT]] ] = [[+5]],},
{[1] = [[!BERSERKER]],[2] = [[MAGIC]],[3] = [[!DROP]],[4] = [[!SORCERER]],[5] = [[!CLERIC]],[6] = [[!ROGUE]],[7] = [[!WARRIOR]],[8] = [[!SELL]],[9] = [[!PALADIN]],[10] = [[!ANTI_PALADIN]],[11] = [[!DRUID]],[12] = [[!SHAMAN]],[13] = [[!ASSASSIN]],[14] = [[!MERCENARY]],[15] = [[!NECROMANCER]],[16] = [[!CONJURER]],[20] = [[!PYROMANCER]],[17] = [[!MONK]],[21] = [[!CRYOMANCER]],[18] = [[!BARD]],[22] = [[!ILLUSIONIST]],[19] = [[!THIEF]],[23] = [[!PRIEST]],[24] = [[!DIABOLIST]],},
{[ [[DAMROLL]] ] = [[+1]],[ [[HITROLL]] ] = [[+2]],[ [[DEX]] ] = [[+2]],[ [[ARMOR]] ] = [[3]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[ [[ARMOR]] ] = [[0]],},
{[1] = [[forage]],[2] = [[obj]],[3] = [[normalizer]],[4] = [[Ranger]],[5] = [[Trophy]],[6] = [[command]],[7] = [[forage]],[8] = [[Ranger]],[9] = [[trophy]],[10] = [[attack]],[11] = [[counter]],},
{[1] = [[!SORCERER]],[2] = [[!CLERIC]],[3] = [[!ROGUE]],[4] = [[!PALADIN]],[5] = [[!ANTI_PALADIN]],[6] = [[!DRUID]],[7] = [[!SHAMAN]],[8] = [[!ASSASSIN]],[9] = [[!NECROMANCER]],[10] = [[!CONJURER]],[11] = [[FLOAT]],[12] = [[!MONK]],[13] = [[!BARD]],[14] = [[!THIEF]],[15] = [[!PYROMANCER]],[16] = [[!CRYOMANCER]],[17] = [[!ILLUSIONIST]],[18] = [[!PRIEST]],[19] = [[!DIABOLIST]],},
{[1] = [[SENSE_LIFE]],[2] = [[FARSEE]],},
{[ [[DAMROLL]] ] = [[+1]],[ [[HITROLL]] ] = [[+1]],[ [[ARMOR]] ] = [[2]],[ [[PERCEPTION]] ] = [[+100]],},
{[1] = [[MAGIC]],[2] = [[!SORCERER]],[3] = [[!NECROMANCER]],[4] = [[!CONJURER]],},
{[ [[CON]] ] = [[+1]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[charm_person_instruments_command]],},
{[1] = [[NO]],[2] = [[FLAGS]],},
{[1] = [[chain lightning]],},
{[ [[ARMOR]] ] = [[+1]],[ [[HITROLL]] ] = [[+3]],[ [[HITPOINTS]] ] = [[+25]],[ [[CHA]] ] = [[+5]],},
{[1] = [[MAGIC]],},
{[1] = [[cure critic]],},
{[1] = [[MAGIC]],},
{[ [[HITROLL]] ] = [[+1]],[ [[HITPOINTS]] ] = [[+10]],[ [[ARMOR]] ] = [[1]],},
{[1] = [[!RENT]],},
{[1] = [[quest_ranger_druid_subclass_heart_limiter]],},
{[1] = [[GLOW]],},
{[ [[ARMOR]] ] = [[0]],[ [[HITPOINTS]] ] = [[+20]],},
}
